- app/lib/sms-games/controllers/logicGameStart.js
Simple fix to a bug: beta version of game (id 201) restarts automatically at auto-start game time delay, regardless if game has already begun. 
We add a check to make sure that the game hasn't already begun. 
Using Postman, I've created 1) games where no one has joined, to confirm that auto-start works, and 2) games where people have joined, to confirm that the game doesn't restart. 
Closes #385.
> fix game auto-start bug

- app/config/smsConfigsLoader.js
- app/lib/ds-routing/config/start-campaign-transitions.json
This fixes two things:
- `logger` was undefined in smsConfigsLoader and so it'd throw an exception when it'd try to log errors
- and then the error it was trying to log was that a Ryan's playbook config was missing
This is the error the server was throwing:
```
[01/08 12:58:45 EST][err] ReferenceError: logger is not defined
[01/08 12:58:45 EST][err]     at EventEmitter.app.getConfig (/opt/run/snapshot/package/app/config/smsConfigsLoader.js:66:3)
[01/08 12:58:45 EST][err]     at MCRouting.campaignTransition (/opt/run/snapshot/package/app/lib/ds-routing/controllers/MCRouting.js:65:30)
[01/08 12:58:45 EST][err]     at module.exports (/opt/run/snapshot/package/app/lib/ds-routing/index.js:26:13)
[01/08 12:58:45 EST][err]     at Layer.handle [as handle_request] …
```
> Ryan's playbook config + logger fix

- app/lib/ds-content-api/index.js
- app/lib/reportback/index.js
- app/lib/reportback/test/reportback.test.js
- mobilecommons/mobilecommons.js
- package.json
Report back submissions will be retried up to 3 times if the response comes back with an error response of some sort. An error is either a response with status code 400, 408, 500 (these are just ones we've commonly seen elsewhere) or a body with a value == FALSE.
Other things:
- Logging the error when a response has a body == FALSE
- Updated the report back test to hopefully fix the random timeout issues we were seeing on tests
Report back submissions are now done with the node-request-retry module. This allows us to retry failed requests and also set a custom callback (`isCampaignsReportBackError`) that determines if a response is valid or not.
The changes here make `createTestDoc` wait until the doc is created before continuing to the next step.
- `$ npm update`
- `$ npm test`
- Ensure …
> Report Back Retry

- app/lib/sms-games/config/competitiveStoriesConfigModel.js
- app/lib/sms-games/controllers/gameMessageHelpers.js
Today, I removed the `endgame_config` object from all SMS game documents on production, and moved the endgame config flags into the `END-GAME` object within the `story` object. 
To support this move, I made attendant changes to `gameMessageHelpers.js` (there are a lot of changes, mostly because I also changed the `storyConfig` variable to `gameConfig`; I reasoned that the variable should be called `gameConfig` so that the developer will not confuse that variable for the `story` object within a game's configuration object.) 
I also removed the `endgame_config` object from the corresponding model. 
After updating your local configuration database, (see the [wiki](https://github.com/DoSomething/ds-mdata-responder/wiki/Configuration) for a guide), running `npm test` should adequately prove …
> remove `endgame_config` from top-level config object, move into `story[END-GAME]`

- app/config/smsConfigsLoader.js
- app/lib/donations/controllers/DonorsChooseDonationController.js
- app/lib/donations/models/donorschooseConfigModel.js
- app/lib/ds-routing/config/campaignStartConfigModel.js
- app/lib/ds-routing/config/startCampaignTransitionsConfigModel.js
- app/lib/ds-routing/config/tipsConfigModel.js
- app/lib/ds-routing/config/yesNoPathsConfigModel.js
- app/lib/ds-routing/controllers/MCRouting.js
- app/lib/ds-routing/controllers/Tips.js
- app/lib/reportback/index.js
- app/lib/reportback/reportbackConfigModel.js
- app/lib/reportback/test/reportback.test.js
- app/lib/sms-games/config/competitiveStoriesConfigModel.js
- app/lib/sms-games/controllers/SGCompetitiveStoryController.js
- app/lib/sms-games/controllers/gameMessageHelpers.js
- app/lib/sms-games/controllers/logicBetaJoin.js
- app/lib/sms-games/controllers/logicGameStart.js
- app/lib/sms-games/controllers/logicUserAction.js
- test/BullyText.js
- test/EndGameFromUserExit.js
- test/GameAlphaStart.js
- test/ScienceSleuth.js
- test/ds-routing.js
This is a minor refactor that defines config model names in a single location at `app.ConfigName`. When getting configs now, instead of using hardcoded strings, we use object properties. Also changed some model names from their plural to singular forms.
- `smsConfigsLoader.js`: Model names defined here
- `*ConfigModel.js`: Plural names changed to singular
- Everything else: Changing from using hardcoded string to app.ConfigName
I tested by running `$ npm test` and sending requests to sms-multiplayer-game, reportback, and ds-routing endpoints to ensure they responded with valid responses.
Closes #389
@tongxiang
> Config name refactoring

- app/lib/ds-content-api/index.js
- app/lib/reportback/index.js
- app/lib/reportback/reportbackConfigModel.js
- app/lib/reportback/test/reportback.test.js
We'll need to update the campaigns on Mobile Commons that are actively receiving report backs before pushing this to production. We should also test on staging before pushing to prod. Trello card to remind us is here: https://trello.com/c/CC8rbPaz/168-sms-report-backs-with-captions
During the report back flow, users will be asked an additional question to provide a photo caption. The order now goes: `photo -> caption -> quantity -> why -> complete`.
- `app/lib/ds-content-api/index.js`: adds a caption field to be submitted with the reportback request
- `app/lib/reportback/reportbackConfigModel.js`: adds a property for us to configure for the caption opt-in path
- `app/lib/reportback/index.js`: The meat of everything. Works pretty much like how we receive the quantity and send the next …
> Reportback Caption

- app/lib/sms-games/controllers/SGCompetitiveStoryController.js
- app/lib/sms-games/controllers/logicBetaJoin.js
- app/lib/sms-games/controllers/playerNameHelpers.js
1. During the game creation process, sends the alpha messages which let her know the names of players she's invited to the game. 
2. When a beta joins, a) sends that beta a message letting her know which players haven't joined yet, b) sends the alpha a message letting her know the name of the beta that's joined, who they're still waiting on, and whether she wants to begin the game, and c) sends a message to already-joined betas telling them who's joined, and who they're still waiting on. 
It does this by: 
During any state change (an alpha creating a game, a beta joining a game), it updates the necessary Mobile Commons user profiles with user name information and then sends the right messages. 
The meat is in `playerNameHelpers.js`, within `createGameInviteAll` and …
> adding player names to the game invite process

- app/lib/sms-games/controllers/SGCreateFromMobileController.js
Fixes the exception that got triggered during a "create game from mobile" process. Basically the config couldn't be found. The name used to find the config for competitive stories changed from "competitive_stories" to "competitive_story." This fixes that.
Plus some minor code formatting.
> Fix for exception during create-game-from-mobile process

- app/lib/sms-games/controllers/playerNameHelpers.js
Changing create-game behavior back to using the `mobilecommons.optin` method. Betas needed to get the message that was set in the "Tell-a-friend" field. But the new way we were doing things just opts them into the path itself.
This does probably break the player name functionality. We'll revisit when we get closer to rolling that feature out.
cc: @tongxiang
> Create game to use mobilecommons.optin

- app/lib/sms-games/controllers/SGCompetitiveStoryController.js
###What does this PR do?
Previously, we'd added autostart functionality **only** to games created with the id of 201, or to the A/B testing version of Science Sleuth. Now, we remove that flag to allow all created games to use the auto-start functionality.
> add autostart for all games

- app/lib/ds-routing/controllers/MCRouting.js
- app/lib/reportback/test/reportback.test.js
- mobilecommons/mobilecommons.js
- test/mobilecommons.js
Updates our usage of the Mobile Commons "optout" API so that the API call no longer requires a "company key" param. This facilitates the normal staff pick flow when a user is opted out of the campaign signup flow and opted into the start campaign flow. 
Also updates reportback and mobilecommons tests. 
Tested with the main DoSomething.org affiliate account by testing with personal phone. Texted "WORN" to opt into the Comeback Clothes 2015 signup campaign. Then, opted out of that signup campaign and into the main start campaign flow with [the DS Start Campaign Post in this Postman Collection.](https://www.getpostman.com/collections/468ccfa1dd5e91d672a3) Then checked my phone's profile on MobileCommons to ensure I've successfully been opted out of the signup campaign. 
Still needs to be …
> Update Mobile Commons API integration to facilitate staff pick functionality across affiliate accounts

- mobilecommons/mobilecommons.js
Fixes how we're actually supposed to be making the mobilecommons `profile_opt_out` call.
> fix optout API call

- app/lib/sms-games/controllers/playerNameHelpers.js
- mobilecommons/mobilecommons.js
- package.json
- test/mobilecommons.js
Code prior to #416 was breaking beta tell-a-friend functionality. But then #416 took out the code that allowed some messages with player names to work. We're reconciling everything. 
Now, messages with player names work, and beta tell-a-friend functionality still works. 
We've added a callback to the `mobilecommons.profile_update` function to make everything work. 
Use [this Postman collection](https://www.getpostman.com/collections/4331949cf475d70cf3db
) to test, perhaps with phone numbers you have access to. Create a game, ensure that the alpha gets a message with the names of the users she's invited, and when betas join, ensure that the proper betas get the right messages. 
I've modified the `Science Sleuth A/B testing` game so that it supports this new feature. This postman collection …
> fix beta opt in profile update

- app/lib/sms-games/controllers/playerNameHelpers.js
- mobilecommons/mobilecommons.js
Minor changes in service of A/B testing player names on onboarding process. 
Doesn't really need to be. Just changed the official name of what the `beta_joined_notify_other_betas_oip` is named in the config file.
> minor changes to facilitate A/B testing player names on onboarding process

- app/lib/sms-games/config/competitiveStoriesConfigModel.js
This PR fixes a bug--previously, we were unable to access the beta_joined_notify_other_betas_oip in playerNameHelpers.js because it wasn't defined within the mongoose model. Everything should work now. 
Creating a game, getting to the beta join point in the game creation process.
> add beta_joined_notify_other_betas_oip to mongoose schema

- app/lib/donations/controllers/DonorsChooseDonationController.js
- app/lib/sms-games/config/competitiveStoriesConfigModel.js
- app/lib/sms-games/controllers/SGCompetitiveStoryController.js
- app/lib/sms-games/controllers/gameMessageHelpers.js
- app/lib/sms-games/controllers/logicUserAction.js
- app/lib/sms-games/controllers/playerNameHelpers.js
- app/lib/string-validators/index.js
- test/BullyText2014.js
- test/BullyText2015ABTest.js
- test/GameAlphaStart.js
- test/_init.test.js
- test/testHelperFunctions.js
A lot has been changed, but the basic functionality of this PR is simple. It: 
1. Adds a new feature: at the end of each level, all players receive a message telling them which players answered correctly (there's a flag right now to make sure this feature only appears for the story id of 301.)
2. Adds tests for this feature. 
3. Adds a new small module with string helper functions (obscenity checkers, etc.). When players enter their names, our apps now add a character limit (10 chars) and check for obscenities. Player names are also now added to user profiles on mobile commons with a more elegant syntax: "Tom, Barry, & Andrea" instead of "Tom, Barry, Andrea". 
**Files to pay attention to:**
1. `playerNameHelpers.js` - this is where the `endLevelMessageWithSuccessPlayerNames.js` function …
> adding player names to end-level feedback

- app/lib/reportback/index.js
- app/lib/reportback/test/reportback.test.js
Previously, if a reportback DB document was created but the reportback was never submitted/finished by the user, it was never destroyed and thus lingered in the database. 
If a user didn't finish a reportback flow, but then wanted to reportback into another campaign, our app would sometimes find their previous unfinished reportback documents and update those documents, messing up the new reportback flow. 
This PR adds a new, campaign-specific param to our DB calls to eliminate this interference. 
`reportback/index.js` contains the modified code. 
By beginning a reportback flow (1/3 Postman collection [here](https://www.getpostman.com/collections/71bd60b99e46cc8ce514
)), stopping at any stage before you submit the reportback, and then creating a new reportback flow. (Comeback Clothes …
> fix bug - unfinished reportback influencing new reportback flow, add tests

- app/lib/sms-games/controllers/SGCreateFromMobileController.js
- app/lib/sms-games/controllers/logicGameStart.js
Fixes some scoping issues. Previously, createGame was no longer accessible within the promise scope. By attaching it to `self`, we've made it so. 
This also checks for the existence of a document in the game auto-start functionality. (Helpful for when a developer is creating games on the local machine, deletes game docs from the database, and then the app throws an error when it can't find that game five minutes later.) 
Creating a game through mobile via postman.
> scoping fix

- app/eventEmitter.js
- app/lib/ds-content-api/index.js
- app/lib/reportback/index.js
- app/lib/reportback/test/reportback.test.js
This adds permalink functionality in reportbacks. That is, when a user finishes a reportback flow by texting back an answer to the question "why is completing this campaign important to you", the completion message they receive contains a url to their custom reportback page. 
The reviewer should start at `app/lib/reportback/index.js`, where the function handling the reportback flow has been updated. 
`npm test`. 
Additionally, use the postman collection below to test with a test reportback flow already set up to return a message with your reportback link: 
```
{"id":"d56424ac-049d-f38d-35da-02ad8327057e","name":"SMS Report Backs - Test","timestamp":1431641139202,"requests":[{"collectionId":"d56424ac-049d-f38d-35da-02ad8327057e","id":"031d50e6-a7af-fd73-878b-857435224553","name":"4) Send …
```
> add reportback permalink functionality

- app/lib/sms-games/controllers/playerNameHelpers.js
Closes #438. Turns on end-level player name logic for all games. 
`npm test`.
> remove 301 story_id end level player name messages checking

- app/lib/reportback/index.js
- app/lib/reportback/reportbackConfigModel.js
- app/lib/reportback/test/reportback.test.js
- package.json
Adds a [library](https://github.com/DoSomething/count-von-count) which filters a text string for numbers and spelled numbers, and converts those numbers to digits. 
This library is added to the reportback flow, where the user-submitted response for the "quantity done" question is then filtered for digits before being submitted to the reportback API. 
If a response with no numbers is submitted, the user receives an error message, which has been added to the reportback config do. 
`npm test` validates whether the user receives the `message_quantity_sent_invalid` message after submitting an invalid message. 
The [library](https://github.com/DoSomething/count-von-count) contains its own tests, and its validity can be tested independently. 
This functionality can also be tested with [this …
> Issue 470: reportback quantity validations

- app/lib/sms-games/controllers/SGCompetitiveStoryController.js
- app/lib/sms-games/controllers/logicBetaJoin.js
- app/lib/sms-games/models/sgGameSchema.js
When a beta joins a game, we mark this event in our game doc with a timestamp. Will help us, in the future, to determine the median amount of time it takes for a beta to join the game. 
Creating a game, having a beta joining a game, and then confirming in the database that a date has been added. 
Closes #473.
> add timestamps to betas joining

- app/lib/sms-games/controllers/logicUserAction.js
Pretty self-explanatory. Reduces the time between end-level messages and start messages--got a lot of feedback from intern testers that the delays between levels (30 seconds until the next level's first message) were too long. Tested on my local with my own phone, messages are sent in order. 
Closes #474.
> reduce end level wait time for messages

- app/lib/sms-games/config/competitiveStoriesConfigModel.js
- app/lib/sms-games/controllers/SGCreateFromMobileController.js
- app/lib/sms-games/models/sgGameCreateConfig.js
- test/CreateGameFromMobile.js
This PR adds a bug fix. (See details of the bug below.) We fix this by: 
1. Adding a timestamp to game create config documents, and querying only for the most recent document. 
2. Creating [a new MData](https://dosomething.mcommons.com/mdatas/12211) with a new query param, `alpha_first_name_query_response`, to the mdata attached to [the first message of the mobile create flow](https://dosomething.mcommons.com/campaigns/135439/opt_in_paths/181501), as well as the ["invalid alpha first name"](https://dosomething.mcommons.com/campaigns/135439/opt_in_paths/181645) message.  
3. Checking for the presence of this query param within `SGCreateFromMobileController.prototype.processRequest` in order to determine whether or not a new game create config doc should be created. If it's present, then …
> bug fix: creating subsequent games from mobile

- app/lib/donations/controllers/DonorsChooseDonationController.js
- app/lib/donations/models/donorschooseConfigModel.js
It changes the DonorsChoose donation flow to match [this new flow](https://docs.google.com/document/d/1CglUNrQ-T93ubuAZ0kt7Sm3otwTPnZ3TLGZF_PoEu70/edit#). 
A few important changes have been made, code-wise:
1. The `findProject` method is now called by the `start` method. 
2. The `donorschooseConfigModel.js` has been changed to reflect new params. 
3. General refactoring to support the new order of messages and new param names. 
`DonorsChooseDonationaController.js`. 
[This Postman collection](https://www.getpostman.com/collections/b6a81618402acc8c598c) should help us test it. 
For some reason, however, the test API doesn't provide results which can be successfully donated to. Once we get the updated credentials from DonorsChoose, we'll test this flow again to confirm. 
Closes #481.
> Add new DonorsChoose donation flow

- app/lib/donations/controllers/DonorsChooseDonationController.js
Limits projects returned to by the DonorsChoose API just to those created before September 14th, 12:01am GMT. 
N/A
How to test? You can switch out the PROJECT_CREATION_CUTOFF_DATE value for an earlier Unix epoch date. For instance, you can use the following value:
`PROJECT_CREATION_CUTOFF_DATE = 1440028860000 // August 20th`
If you switch the value out for a date early enough, you should start seeing projects being returned which were created earlier than that date. (Which I manually verified by going to the Donorschoose site, finding that project, and confirming that it was created earlier than the specified date.) 
Closes #494.
> add project created by time limit to donorschoose search

- app/lib/donations/controllers/DonorsChooseDonationController.js
Changes the DonorsChoose API call to make the donation **on behalf of** the user, instead of creating a an account associated with that user's email address. 
Correspondence with DonorsChoose team: 
Along the lines of feedback… our operations team highlighted one potential sticking point for our donors, and I wanted to see if it’d be possible to tweak the mechanics of the program for the remainder of the program. When someone completes the game, the game currently asks them for their email address to share the teacher’s note—which then creates a new donor account for them in our database. We’re a little concerned that this could be a problem, since we’re not telling the users that we’ll be creating accounts for them on DonorsChoose.org. For those who don’t want to sign up for our site …
> change user to become honoree in donation API call

- package.json
Closes #457 by bumping version number to 1.0.0, and before myself or anybody else jumps back into this repo to break things. Per [semver.org](http://semver.org/#how-do-i-know-when-to-release-100):
> If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you’re worrying a lot about backwards compatibility, you should probably already be 1.0.0.
Looking to start using Gitflow releases moving forward for this repo. Per the [Gitflow release branching model](http://nvie.com/posts/a-successful-git-branching-model/#release-branches), this would be our order of operations:
Somewhere in here we'd deploy our changes to Heroku too... 🚒 🎆 🔥
> Bumped version number to 1.0.0

- .gitignore
Closes #522. 
Running app locally with `heroku local` reads environment variables from a `.env` file.
> Include .env in .gitignore

- app.json
- package.json
- server.js
Removes the `newrelic` package to cut down on some [New Relic messages](https://github.com/DoSomething/ds-mdata-responder/issues/518#issuecomment-233358812) we're seeing in production:
>  {"v":0,"level":10,"name":"newrelic","hostname":"Aarons-MacBook-Pro-2.local","pid":1029,"time":"2016-07-19T21:13:04.305Z","msg":"Not creating segment \"timers.setTimeout\" because no transaction was active","component":"tracer"}
Run `heroku local` before and after to verify this branch stops the `newrelic` logs.
Deploying to prod will complete step 2 in #518
> Removes NewRelic package

- app.json
- newrelic.js
- package.json
- server.js
Sorry, New Relic, it seems you [were noisy](https://github.com/DoSomething/ds-mdata-responder/issues/518#issuecomment-233358812) because we had our logging level set to `trace` this whole time. I've set you to `info` and things are looking a bit more peaceful ✌️ 
Refs discovery in https://github.com/DoSomething/ds-mdata-responder/pull/533#discussion_r71787107
My guess is when we first opened this issue for NO coverage, we were looking for New Relic coverage within our standard DS list of applications (prob what Nodejitsu was using), and not the Heroku add-on.
Dare I say this closes #518.
cc @mshmsh5000
> Adds New Relic package

- app/lib/donations/controllers/DonorsChooseDonationController.js
- mobilecommons/mobilecommons.js
* Removes a hardcoded `olderThan=1445299201000` (Tue, 20 Oct 2015 00:00:01 GMT) query string param to get results back from the DonorsChoose API. Fixes #520, refs https://github.com/DoSomething/ds-mdata-responder/issues/539#issuecomment-236728667
* Adds `debug` logging to `DonorsChooseDonationController` and `mobilecommons.profile_update`
Run locally and POST to `http://localhost:5000/donations/donors-choose/start?id=201` with your phone number. You should receive a "Awesome we want [teacher name].." message back, instead of the "Oof! Something went wrong message".
Can additionally inspect queries in browser:
* [New request URL](http://api.donorschoose.org/common/json_feed.html?&subject4=-4&sortBy=2&costToCompleteRange=10+TO+10000&max=1&APIKey=DONORSCHOOSE)
* [Initial request URL (with …
> Removes hardcoded DonorsChoose olderThan param

- app/lib/donations/controllers/DonorsChooseDonationController.js
* Updates the DonorsChoose QA URL in attempt to fix #547.. but was getting a [statusCode 6](https://data.donorschoose.org/docs/transactions/project-donations/) when testing with QA credentials. Currently getting an error back that QA service is currently unavailable.
* Adds more `debug` logging to DonorsChoose flow
* Refactors `submitDonation` function to use already defined `donorsChooseApiKey`, `donorsChooseApiPassword`, and `DONATE_API_URL` variables instead of additional `apiInfoObject` object param
Test locally against the [Donations endpoints](https://github.com/DoSomething/ds-mdata-responder/wiki/api#donations) with`process.env.LOGGING_LEVEL = debug`  to confirm requests are being sent to updated URL per #547 
Waiting to hear back from DonorsChoose team for guidance on the …
> DonorsChoose QA URL

- app/lib/ds-content-api/index.js
- app/lib/reportback/index.js
- mobilecommons/mobilecommons.js
* Changes email address for new users to `@mobile.import` to fix #557 
* Adds a whole lot of `logger.log('debug', messages)` to watch the Phoenix go by
* Sets default values for `phone` in `findUserUidThenReportBack` and `createUserThenReportback` 
* Pull down and submit a reportback by posting against local `reportback` endpoint with 2 **brand-new-to-DS** US phone numbers:
* Verify new users are created in Thor. They should have emails without the leading 1:, e.g. `2125555555@dosomething.org`
From @DFurnes:
> The `dosomething_northstar` module automatically strips out `@@mobile` when forwarding to Northstar (so the user only has a phone number), so we’d probably want to update it to do the same for `@mobile.import`s.
> Changes new user emails to valid @mobile.import address

- app/lib/donations/controllers/DonorsChooseDonationController.js
- app/lib/donations/donations.js
* Closes #566: Renames `retrieveLocation` function as `retrieveZip`, and changes it to call `findProject` with new param for `zip` to filter projects query by (instead of posting to itself with the `_post` function).
* Removes deprecated `/donations/donors-choose/find-projects` route and related `DonorsChooseDonationController.post()` function and `DonorsChooseDonationController.host` property
* Removes deprecated retrieve projects by state functionality. Less code, less moving parts
* Changes the `start` function to opt user into the `oip_ask_zip` if `max_donations_allowed` has not been reached. Previously the `start` function would simply call `findProject` without filtering for zip.
* For now, uses a hardcoded `donorsChooseConfig` variable to DRY instead of constantly reading calling …
> Science Sleuth Donations: collect zip and filter Projects query

- app/lib/donations/controllers/DonorsChooseDonationController.js
- mobilecommons/mobilecommons.js
Extracts the code from `findProject` that creates a `donation_infos` document and calling Mobile Commons into a separate `createDonationDoc(mobileNumber, selectedProposal)` function. Similar to #571, no new functionality introduced. This is to help keep the code readable, and make it easier to work on #550 and #552 .
Also adds error handling to the beginning of `findProject` instead of an `else` at the end to cut down on brackets / nesting 🐦 
Pull down locally, post to the `retrieve-zip` endpoint to verify expected behavior.
> DonorsChooseDonationController.createDonationDoc

- app.json
- app/lib/donations/controllers/DonorsChooseDonationController.js
- app/lib/donations/donations.js
This isn't a completely 100% dev complete Science Sleuth, but it does submit donations to the DC API, and it's quite a bit of changes - so merging into`develop` now to keep future pull requests readable.  Here's what's going on:
* Refactors Donors Choose Science Sleuth donations to use a single endpoint: `/donations/donors-choose`, inspired by how [custom Slack apps use a single Action URL](https://api.slack.com/docs/message-buttons) to implement custom actions.
* Removes now deprecated endpoints and related functions
* `/donations/donors-choose/start`
* `/donations/donors-choose/retrieve-firstname`
* `/donations/donors-choose/retrieve-email`
* `/donations/donors-choose/retrieve-zip` 
* Removes unnecessary donation controller interface code to simplify codebase
* Refactors Donation MoCo …
> Donations chatbot

- app/lib/donations/controllers/DonorsChooseDonationController.js
- app/lib/donations/donations.js
- app/lib/donations/models/donorschooseConfigModel.js
* Refactors the model of the `donorschoose` collection in the `config` database to store the Donations chatbot copy and opt-in-paths in Mongo instead of hardcoding. (refs todos in #573)
* Renames functions for better code readability:
* `chat` renamed to `chatbot`
* `respondAndListen` renamed to `chat`
* `respond` renamed to `endChat`
* `respondWithGenericFail` renamed to `endChatWithFail`
* `requestDonation` renamed to `postDonation`
* Set your local `DONORSCHOOSE_MOCO_CAMPAIGN_ID` to our staging MoCo Campaign ID
* Same steps as #573, testing flow locally to make sure nothing has changed
* Edit values in the `donorschoose` document for the MoCo Campaign ID, restart, and confirm message copy has changed
Need to add additional `msg_` properties to the `donorschoose` for naughty language, …
> Donations chatbot configuration

- server.js
Requires the New Relic package on line 1 (refs original description in #518), hoping this will get errors showing up in New Relic to finally close out #518.
Per [docs](https://docs.newrelic.com/docs/agents/nodejs-agent/troubleshooting/troubleshooting-your-nodejs-installation) and suggestion from New Relic support:
> Ensure that you have added `require('newrelic')`; as the first line of the app's main module. If the `require` is added later, the Node.js agent may not properly instrument your application.
Pull down locally and start up app via `heroku local`. Verify connection to New Relic in your `newrelic_agent.log`.
We're soon looking to change our New Relic integration to use our standard DS.org license key instead of our Heroku add-on license key (essentially undoing …
> Require New Relic on line 1

- app/lib/donations/controllers/DonorsChooseDonationController.js
- app/lib/donations/models/donorsChooseConfigModel.js
* Adds a `DONORSCHOOSE_MAX_DONATIONS_ALLOWED` environment variable to check against's a member's Donation Count to determine whether they can start a Donation conversation.
* Adds a `msg_max_donations_reached` property to the `donorschoose` config collection to set the relevant copy to display when a member has reached the max # of donations possible
Pull down locally and post against the `/donors-choose/donations` endpoint, testing with different numeric values for `profile_ss2016_donation_count` to verify the `msg_max_donations_reached` copy is displayed when given value >= `MAX_DONATIONS_ALLOWED`
Limit first introduced in #482
Closes todo item in #573
> Limit number of donations to a MAX_DONATIONS_ALLOWED environment variable

- app/lib/donations/controllers/DonorsChooseDonationController.js
- app/lib/donations/models/donorsChooseConfigModel.js
* ~~Adds support for a new `DONORSCHOOSE_CLEANSLATE_KEYWORD` that will reset a member's Donation Count if corresponding new `DONORSCHOOSE_CLEANSLATE_ENABLED` is set to `true`. It also attempts to reset the member's `first_name`, `email`, and `postal_code` but for now we'll need to manually reset those in Mobile Commons by editing the profile~~
* Adds a `msg_searching_by_zip` configuration property to inform a donor (both first time and returning) that we're finding a project within their zip code.
* Supports MoCo Liquid style variable for postcode: A `msg_searching_by_zip` value of `'Finding a school in your zipcode {{postal_code}}...'` will render as "Finding a school in your zipcode 94117..." per calling String `replace` method in our `sendSMS` method.
* Fixes a bug saving the user's …
> Saving email fix + Searching By Zip message

- app/config/smsConfigsLoader.js
- app/lib/donations/controllers/DonorsChooseDonationController.js
- app/lib/donations/donations.js
- app/lib/donations/models/donorsChooseBotModel.js
- app/lib/donations/models/donorsChooseConfigModel.js
* Stores our chatbot `msg` properties into a new `donorschoose_bots` collection in `config` DB, instead of `donorschoose` collection -- separating chatbot copy from Mobile Commons configuration.
* Refactors `this.dcConfig` as 2 new properties: `this.mocoConfig` and `this.bot`
* Adds corresponding `DONORSCHOOSE_BOT_ID` environment variable to set the `donorschoose_bot` to use during our current `DONORSCHOOSE_MOCO_CAMPAIGN_ID`
* Adds a `POST /donations/donors-choose/sync` endpoint which queries the new Gambit Jr. API endpoint `donorschoose_bots` to populate `msg_` values in existing `donorschoose_bots` config documents
* Request must include an `api_key` in request body, must match new config variable `GAMBIT_API_KEY` (refs #576)
* Does not automatically create a new `donorschoose_bots` …
> Load DonorsChoose bot messages from new Gambit Jr. API

- app/lib/donations/controllers/DonorsChooseDonationController.js
- app/lib/donations/models/donorsChooseBotModel.js
- app/lib/donations/models/donorsChooseConfigModel.js
- app/lib/donations/models/donorsChooseDonationModel.js
* Fixes a bug setting the Donation Count profile field upon first donation
* Adds  `DONORSCHOOSE_BOT_ID` and `DONORSCHOOSE_MOCO_CAMPAIGN_ID` constants set from environment variables, stores in the `donorschoose_donations` collection
* Adds comments for functions, general code cleanup  (refs #573)
* Remove the value from your Donation Count profile field (we're using `ss2016_donation_count` for this year's run) and then test locally with this branch.
* Confirm MoCo Campaign ID and DonorsChoose Bot ID are stored upon successful donation
Fixes #581, #582
> DonorsChooseDonationController cleanup

- app/router.js
Prevents logging invalid api key warning on GET requests.  
Test GET, and POST with/without sending a `x-gambit-api-key`.
Small bug introduced in #586
> Only warn for invalid API key on POST

- app/config/smsConfigsLoader.js
- app/lib/donations/controllers/DonorsChooseDonationController.js
- app/lib/donations/models/donorsChooseConfigModel.js
- app/lib/donations/models/donorsChooseMocoCampaignModel.js
* Changes `config.donorschoose` collection name to `config.donorschoose_moco_campaigns`. I've manually renamed the collection name in Compose to keep our deprecated documents from 2014 and 2015 stored in the same collection.
* Refactors `oip_chat_ended` as `oip_success` and `oip_error`
* Minor cleanup to `smsConfigsLoader.js`
Verify Staging DonorsChoose chatbot works upon deployment of this branch.
Fixes #587 
Fixes #588
> Science Sleuth tweaks

- api/controllers/DonorsChooseBotController.js
* Changes hardcoded "Teacher says" copy in 2nd success message sent upon completing a DonorsChoose donation.
Locally:
Post required params to `/v1/chatbot?bot_type=donorschoose` to confirm copy change.
Staging:
Text in keyword for staging DonorsChoose campaign upon deploy to staging server.
Hardcoding this copy was one of the tradeoffs made when we made the move from configuring our message content from editing Mobile Commons OIP Conversations  into the Gambit Jr. API.  We could potentially add this to our own internal `{{postal_code}}` Liquid-esque logic we're doing [here](https://github.com/DoSomething/gambit/blob/280d095765cd58261ef2217e4997c8279d353369/api/controllers/DonorsChooseBotController.js#L410), but it also seems easy enough to keep hardcoded for now, since we don't run …
> DonorsChoose success message copy change

- api/controllers/DonorsChooseBotController.js
- api/controllers/SlothBotController.js
- lib/mobilecommons.js
* Moves the `/api/controllers/DonorsChooseBotController.sendSMS` function into our `/lib/mobilecommons` class as a new `chatbot` function to DRY setting the `gambit_chatbot_response` Mobile Commons Custom Field value used for chatbot Mobile Commons campaigns.
* Updates `/api/controllers/SlothBotController` accordingly to DRY
Test that our staging DonorsChooseBot and SlothBot Mobile Commons Campaigns are operational upon deploy to staging. 
Will use this to begin prototyping a DS Campaign Bot to eventually deprecate our `api/legacy` endpoints.
#463
> Adds mobilecommons.chatbot function to DRY

- api/controllers/CampaignBotController.js
- api/models/ReportbackSubmission.js
- api/router.js
- documentation/endpoints/chatbot.md
- lib/mobilecommons.js
- lib/phoenix.js
Groundwork for #606, opening now to merge to keep this pull request readable. 
* Adds new `function campaignGet(campaignId, callback)` to `/lib/phoenix.js`. Also renames `global.dscontentapi` to `global.phoenix`
* Adds new `/api/controllers/CampaignBotController` to be used when `bot_type=campaign&campaign=:campaign_id` is passed to our chatbot endpoint, loading the Campaign from Phoenix
* If `&start=true`. displays signup message for Campaign Title
* Else write whatever our member texts back as `quantity` to a new `reportback_submissions` collection in our operations database (`mdata_responder`)
Post locally to `/v1/chatbot?bot_type=campaign&campaign=2070` to load Bumble Bands campaign from API, confirm a `reportback_submission` document is created upon including numeric `args` when …
> Starts on CampaignBot + ReportbackSubmissions

- api/controllers/CampaignBotController.js
- api/models/Campaign.js
- api/models/User.js
- api/router.js
- config/smsConfigsLoader.js
* Adds a`campaigns` collection to `configs` database to cache Campaigns from Phoenix API. Right now this is manually imported for development, but we'll eventually want to build ways to programatically refresh
* Refactors CampaignBotController  to load its Campaign from the relevant `app.config` instead of querying Phoenix API in every Gambit `chatbot?bot_type=campaign` API request (see #609)
* Adds `user_id` and `incoming_request` properties to our Express request in `router.js` to DRY code in SlothBotControllers and DonorsChooseDotControllers in upcoming pull requests
* Adds a `users` collection to our `mdata-responder` operations database as groundwork for storing a User's campaign activity. Upon posting to the Campaignbot chatbot request, we either create a new user document if one …
> Adds User and Campaign models

- api/controllers/CampaignBotController.js
- api/models/campaign/ReportbackSubmission.js
- api/models/campaign/Signup.js
Picks up where #611 left off and adds support for additional Reportback Submissions after the first. Still not posting anything to API yet -- just storing data in the Gambit DB for prototyping.
* Renames the Signup`reportback_submission` property as `draft_reportback_submission` 
* Adds a `submitted_at` Date property to Reportback Submissions to store the time saved to `reportback_submissions` DB and posted to Phoenix API. We are not deleting `reportback_submissions` documents -- which is slight departure from how our `/api/legacy/reportback` controller [deletes documents from the `reportbacks` collection upon successful post to the Phoenix API](https://github.com/DoSomething/gambit/blob/0eee555eb58472bfbca293007610662082f834b0/api/legacy/reportback/index.js#L447).
* Adds a …
> Repeat Reportback support

- api/controllers/CampaignBotController.js
Nothing user-facing, cleans up code readability:
* `chatReportback(isNewSubmission)` refactored as `startReportbackSubmission()` and `continueReportbackSubmission()`
* Moves signups query logic out of `chatbot` and into separate `loadSignup(signupId)` function
Verify reportback conversation still works per #613
Next up:
#606
> Splits chatReportback into start and continue functions, adds loadsSignup

- api/controllers/CampaignBotController.js
Still nothing user-facing, leftover function from #614 moving handling creating a User into a `createUserAndPostSignup` function.
* Adds a `GAMBIT_CMD_REPORTBACK` config variable to avoid hardcoding the Start Reportback command.
* Renames `users`, `signups`, and `reportbackSubmissions` variables with a `db` prefix.
* Need to manually delete your user in the `users` collection
* Start and complete, repeat campaign
* This branch also adds comments about how a User's `campaigns` hash table property is meant to store the Signup status for a given Campaign's current run. We'll need to add logic to query for Campaign start/end dates and verify if our Signup `created_at` date is current (if not, we'll need to create a new Signup)
* Not posting anything to Phoenix API yet. It does seem worth …
> Adds createUserAndPostSignup function

- api/controllers/CampaignBotController.js
Adds a check for a `start` query param within `continueReportbackSubmission`. If it exists:
* Send a "Picking up where we left off..." message to the user
* Send additional message asking the **next question** for collecting Reportback info
* Clear out your User's `campaigns` property in the `users` Mongo collection to clean slate Campaign Activity
* Text in Campaign's Mobile Commons keyword to load CampaignBot and create new Signup
* Begin a Reportback by texting in our `CMD_REPORTBACK`
* Text in the Campaign's Mobile Commons keyword again to continue conversation
* Confirm you're sent the "Picking up where we left off" message, and then asked for Quantity
* Respond with quantity, and then repeat texting in keyword again to confirm asked for Caption
* etc
We set the `start` query string …
> Better support for continuing unfinished Reportback Submissions

- api/controllers/CampaignBotController.js
Refactors `CampaignBotController` functions to pass the Express request and response down to the `sendMessage(req, res, msgTxt)` function (refs #618) and [SO thread on scoping data in Express](http://stackoverflow.com/questions/20710023/how-to-scope-data-in-express-node-controller/20710437#20710437).
* Removes `self.incomingMsg` in favor of always inspecting `req.incoming_message`
* Removes hardcoded `@stg:` prefix from messages and appends in `sendMessage(req, res, msgTxt)` if our `NODE_ENV` is not production
* Calls `response.send()` upon successfully sending a message (instead of immediately upon finding a Campaign)
* Adds "Picking up where we left off" continue message logic into `sendMessage` to send a single message instead of 2 (where often the Picking up message would send after …
> CampaignBot sendMessage cleanup

- api/controllers/CampaignBotController.js
- api/models/campaign/Campaign.js
- lib/mobilecommons.js
Removes hardcoded CampaignBot Mobile Commons `chatbot` opt-in path, supporting multiple DS Campaigns via creating mData's to post to the relevant`/v1/chatbot?bot_type=campaign&campaign=:id` endpoints.
* Adds a `current_mobilecommons_campaign` and `staging_mobilecommons_campaign` to our Campaign model. Loads the Chatbot Mobile Commons Campaign based on value set, and opts member into the `oip_chat` Opt-in path to display our saved `gambit_chatbot_response` custom field value in Mobile Commons.
Also fixes bug on first signup introduced in #619 
Test reportback conversations against Campaigns 2070 and 2299, which I've configured in our DB:
- POST `/v1/chatbot?bot_type=campaign&campaign=2070&start`
- POST `/v1/chatbot?bot_type=campaign&campaign=2070`
- POST …
> Adds CampaignBot support for multiple DS Campaigns

- api/controllers/CampaignBotController.js
- api/router.js
- config/smsConfigsLoader.js
* DRY debug logging with a `loggerPrefix(req) function
* DRY error handling with a `CampaignBotController.handleError(req, res, error)` function
* Set our local User id to `profile_northstar_id` with a big `todo` for when a member joins DoSomething via SMS and we don't have a Northstar ID yet
Chat with the 2 staging CampaignBots and verify app logs look 👍 
Sample `debug` logging:
````
4:04:51 PM web.1 |  info: Express server listening on port 5000 in thor mode...
4:04:56 PM web.1 |  debug: campaign:2070 user:5547be89469c64ec7d8b518d incoming_message:40
4:04:56 PM web.1 |  debug: campaign:2070 user:5547be89469c64ec7d8b518d loaded user:5547be89469c64ec7d8b518d
4:04:56 PM web.1 |  debug: campaign:2070 user:5547be89469c64ec7d8b518d loaded signup:57d09b505a5be8da0feb6739
4:04:56 PM web.1 | …
```
> Stores Northstar ID for User _id, adds handleError and loggerPrefix helper functions

- api/controllers/CampaignBotController.js
- documentation/endpoints/chatbot.md
* Adds more `debug` messaging for logging saving Reportback Submission properties
* Changes lots of `this.handleError` calls introduced in #621 to `self.handleError` 
* Cleans up our Mongoose create methods, no need for a `then`
* Run through user creation, signup, and repeat reportbacking on a CampaignBot
Converting this class to ES6 sounds nicer and nicer as it grows up
#606
> Adds debug logging for continueReportbackSubmission conversations

- api/controllers/CampaignBotController.js
- api/controllers/DonorsChooseBotController.js
- api/models/campaign/CampaignBot.js
- api/models/donation/DonorsChooseBot.js
- api/router.js
- config/smsConfigsLoader.js
- documentation/README.md
- documentation/endpoints/chatbot.md
- lib/gambit-junior.js
Loads CampaignBot message content from the Gambit-Jr. API instead of hardcoding.
* Adds `/api/models/campaign/CampaignBot.js` to model a CampaignBot returned from new `/campaignbots/` endpoint in Gambit-Jr API : http://dev-gambit-jr.pantheonsite.io/wp-json/wp/v2/campaignbots
* Adds a `CampaignBot` property called `bot` to the `CampaignBotController`.  Sends the relevant bot property as the message to our User, instead of using hardcoded copy in helper functions 
* Removes deprecated helper functions
* Adds a `/lib/gambitJunior` helper class to DRY syncing our Bot configs with Gambit-Jr API
Test full CampaignBot conversation flow, including sending invalid quantity / not submitting photo.
Verify that nothing breaks, and messages sent are aligned with [CampaignBot 41's …
> Pull CampaignBot message content from Gambit-Jr campaignbots API

- api/controllers/DonorsChooseBotController.js
- lib/donorschoose.js
* Adds new `olderThan` parameter to `getProposalsQueryUrl` function
* Passes  `process.env.DONORSCHOOSE_PROPOSALS_OLDERTHAN` to filter by
* Set local `DONORSCHOOSE_PROPOSALS_OLDERTHAN` to 1472688000000 and run DonorsChooseBot to confirm donation works
* Unset and test again to confirm donation works
Fixes #625 
cc @sergii-tkachenko
> Adds support for olderThan DonorsChoose query param

- api/controllers/CampaignBotController.js
- api/models/User.js
- api/models/campaign/ReportbackSubmission.js
- api/models/campaign/Signup.js
- api/router.js
- config/connectionConfig.js
- config/connectionOperations.js
- config/index.js
- lib/helpers.js
- server.js
To the end user, all this PR does sync an existing Signup from Northstar if you've already signed up for the DS Campaign XYZ, but it's your first time texting into the CampaignBot for XYZ.
It also refactors the monolithic `CampaignBotController.constructor` callback hell into smaller functions, and moves handling our Express response into `router.js` per @deadlybutter's suggestion in https://github.com/DoSomething/gambit/pull/631#discussion_r80523908
Plus:
* Refactor functions like `collectQuantity` and `collectPhoto` into a `collectReportbackProperty(req, property, ask)` function
* Adds a `getCurrentSignup` req to call Northstar JS Signups.index and check for existence of Signup. TODO -- Check for `Signup.campaignRun.current` right now it's hardcoded to just use first Signup returned
* …
> CampaignBot router + refactor

- api/controllers/CampaignBotController.js
- api/models/Signup.js
- api/models/User.js
- config/router-chatbot.js
- documentation/endpoints/chatbot.md
- package.json
* Adds support to send Signup confirmation messages from CampaignBot for external (non Gambit) Signups:
* Clients like Quicksilver should post to the `chatbot` endpoint and pass the `signup_id` and its `signup_source`
* If the incoming `signup_source` is equal to the Gambit `DS_API_POST_SOURCE`, we don't send the confirmation message (we'll have already sent it to the User after they signed up through Gambit)
* Refactors `CampaignBotController` methods like `getUser` and `cacheSignup` as [Mongoose static and instance methods](http://mongoosejs.com/docs/guide.html#methods) in the relevant model classes
* Adds Bluebird to promisify the new static/instance methods 
code 👀 
staging 📲 
#642
> CampaignBot support to send confirmation messages for external signups

- api/models/Campaign.js
- config/locals.js
- lib/mobilecommons.js
- package.json
- Adds some new packages
- Adds new fields to campaign model
- Creates mobile commons groups per campaign
- Saves ID's to model
LOL this is fun. So when testing in Mobile Commons, you cannot simple "delete" a group. You have to rename the group to some random string, then delete it. MoCo reserves the string in namespace even after you delete it.
Part 2 of this will be exposing this data
Fixes #
> Creates mobile commons groups & saves to DB

- app/models/User.js
Sets a different env variable to keep User registration source as `sms` -- per legacy `reportback` endpoint
Find someone who doesn't have a DS Mobile Commons Profile, or post a dummy number to Thor like I do
Fixes #694
> Post separate User Registration source value

- app/models/Campaign.js
- lib/groups.js
- server.js
- Adds gambit groups API lib
- Makes calls to Gambit Groups API. **Requires dot env file update!**
- Creates groups for campaigns if not present on the campaign
Good lord. Heres the TLDR, it works:
If you want to test this 100% through, you need to be really careful.
1. Delete the campaigns in your local DB.
2. Delete the group in the gambit groups prod DB.
3. Search mobile commons groups on there site for `campaign_id=some id`
4. Keep that tab open & open all 6 results into a new tab.
5. Rename each of those groups with some added random text. (We should probably start doing deleteme or some string that groups them together, sorry)
6. In that tab from step 3, select all of the groups & delete all.
7. Run Gambit.
HAVE FUN!
I need a cookie if you're gonna make me write this one out again. …
> Groups api

- app/controllers/CampaignBotController.js
Prevents User from submitting a photo (without a text response) for the Reportback Submission `caption` or `why_participated` -- resulting in null data on the DS backend.
Locally: 
- Don't pass `args`, only pass `mms_image_url` when responding to Ask Caption or Ask Why Participated, mimicing the response we receive from Mobile Commons if a user responds with an image and no text. 
- Verify the message returned is the Ask message, prefixed with "Sorry I didn't understand that".
Staging: 
- Text CampaignBot and send an image without any text for Caption, and Why Participated.
- Verify you're prompted to send the Caption/Why again, until you send a text response.
This is minimalist fix. It hardcodes the text "Sorry, I didn't understand that" and then repeats whatever the Ask message was. …
> Ensure response contains text when asking for caption or why_participated

- Procfile
- server.js
Going wayyy back in the days of Node, max sockets was capped at 5. Developers had to manually increase this. However by v0.12, this was fixed to always be infinity. https://nodejs.org/en/blog/release/v0.12.0/
By capping this at 100, we're severely hurting ourselves, and it seems to correlate with the requests per minute chart in Heroku, where we keep taking large batches of ~100 requests and then do almost nothing
> Removes old HTTP max sockets code

- .dockerignore
- Dockerfile
- Procfile
- README.md
- docker-compose.yml
- package.json
- server.js
- Updates winston-mongodb to latest version (Had NPM error blocking startup)
- Updates Procfile command
- Adds Dockerfile & dockerignore
This repo itself should be build-able. However to run it you'll need to use the Docker Compose file [here](https://github.com/DoSomething/gambit-services/blob/master/docker-compose.yml)
In order to test the build process still works on Heroku I made a deploy with this branch to staging,
- The build log is here (Looks ✅ ) https://dashboard.heroku.com/apps/ds-mdata-responder-staging/activity/builds/ef1ca1a8-63e6-4bbc-822a-c71686d3b693
- The logs following the app start also seem good
As we start moving towards more services, docker compose will make it much easier for developers to get up & running with Gambit using a consistent image across all …
> Adds Docker support to Gambit

- package.json
Allows patch and minor updates to winston-mongodb, see https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004
`npm install`
May have caused recent crashes on Gambit prod with the following stacktrace:
```
MongoError: index not found with name [timestamp_1]
at Function.MongoError.create (/app/node_modules/mongodb-core/lib/error.js:31:11)
at /app/node_modules/mongodb-core/lib/connection/pool.js:483:72
at authenticateStragglers (/app/node_modules/mongodb-core/lib/connection/pool.js:429:16)
at Connection.messageHandler (/app/node_modules/mongodb-core/lib/connection/pool.js:463:5)
at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:309:22)
at emitOne (events.js:96:13)
at Socket.emit (events.js:191:7)
at readableAddChunk (_stream_readable.js:176:18)
at …
```
> Allow patchlevel  and minor updates to winston-mongodb

- server.js
I explicitly added options to increase connection timeout threshold to 30000 and also enabling keepAlive.
Based on this thread in stack overflow
http://stackoverflow.com/questions/38486384/mongodb-connection-to-mongolab-timing-out-in-nodejs-on-heroku
- follow steps to get gambit up and running in localhost
- Test chatbot endpoint by signing up to a campaign using Postman and following this docs: https://github.com/DoSomething/gambit/blob/develop/documentation/endpoints/chatbot.md
A failed signup showed that there seems to be a hangup happening at the time of upserting data to our Mongo database.
Log is here: https://gist.github.com/rapala61/b165ec13f77ff9500937ee8c0ac4ce17
Related to: https://github.com/DoSomething/gambit/issues/810
> Mongo keep alive

- app/routes/chatbot.js
Previously, when Northstar is unreachable/fails we were not "catching" this failure. This has been shown to lock the main process, potentially leading to Timeout errors seen in Gambit production.
This PR properly catches the error and allows the app to log and respond with an appropriate 500 error.
- Start Gambit in local development env
- change the .env variable DS_NORTHSTAR_API_BASEURI and point to a non-existent URL
- POST a signup with keyword using POSTMAN to your local Gambit
- You should get back an error with a 500 code.
Solves Issue https://github.com/DoSomething/gambit/issues/832
Potentially solves issue https://github.com/DoSomething/gambit/issues/810
References https://github.com/DoSomething/gambit/issues/704
> Catches the rejection at User.lookup in the loadCampaign promise

- lib/phoenix.js
I'm removing the logger instance that is being used in the fetchCampaign function on the lib/Phoenix module. This is the main suspect of introducing the leak. This pull is primarily an experiment, based on the findings of comparing 2 Heap Snapshots. One taken at 9:46:51pm last night (4/4/17) and the second taken at 8:47:06am this morning (4/5/17).
Nothing should change functionally in the app. I think this should just be a visual check.
Reviewed Snapshots captured in staging environment. There seems to be references to kept log strings as well as Winston logger scopes that are not being collected by the GC.
Pull request that introduced the memory leak
https://github.com/DoSomething/gambit/pull/825
Issue to implement fix for memory leak
https://github.com/DoSomething/gambit/issues/842
> removing logger instance from exported function in lib/Phoenix.js

- package.json
Fixes mistake of setting New Relic version number to 1.3 in https://github.com/DoSomething/gambit/pull/841/files#r109963622. I was editing the version number locally to see if I could replicate the failed builds that were failing on the Native Metrics module, but for sure didn't mean to set it to 1.3.
I caught this by checking the staging logs after texting in a staging keyword and found `TypeError: newrelic.addCustomParameters is not a function`. 
Upon stage deploy, verify that doesn't happen :\
> Fix New Relic version number

- app/routes/campaigns.js
- lib/groups.js
Queries the new MGAPI `/api/v1/mobilecommons-groups` endpoint (https://github.com/DoSomething/messaging-groups-api/pull/13) to get the Doing and Completed Group ID's for each Campaign.
* Add a keyword to Thor via Gambini for a Campaign that has never run on Gambit before. I used 1524
* GET /campaigns to Gambit API and verify Doing and Completed groups are returned:
```
{
"id": "1524",
"title": "Bubble Breaks",
"status": "active",
"current_run": "6242",
"keywords": [
{
"keyword": "BUBBLEBOT"
}
],
"mobilecommons_group_doing": 296582,
"mobilecommons_group_completed": 296588
},
```
* Verify Mobile Commons Groups are created:
Gambit no longer handles creating Mobile Commons Groups that don't exist for a given Campaign/Run/Environment, it's work done by the [**GET** `/mobilecommons-groups` …
> Fix Messaging Groups creation for new Campaign Runs

- app.json
Removes deprecated `CAMPAIGNBOT_CAMPAIGNS` from` app.json` (required for Review apps)
Missed this in #841
> Removes deprecated CAMPAIGNBOT_CAMPAIGNS from app.json

- app/exceptions/UnprocessibleEntityError.js
- app/routes/campaigns.js
Splits up **POST** `/campaigns/:id/message` into middleware and adds `req.timedout` checks.
Using Thor:
* 200: **POST** `/campaigns/7/message` with type `scheduled_relative_to_signup_date`
* 422: **POST** `/campaigns/7/message` with type `scheduled_relative_to_reportback_date` -- We don't have a default `scheduled_relative_to_reportback_date` set.
* 404: **POST** `/campaigns/723423/message` with type `scheduled_relative_to_signup_date`
* 422: **POST** `/campaigns/362/message`-- Campaign is closed
* 422: **POST** `/campaigns/62/message` -- Campaign is not running on Gambit (no keywords)
Technically we shouldn't close #504 without adding the `req.timedout` checks into the GET campaigns endpoints, but those are only used internally by Quicksilver to cache Campaigns, and good ol' Slothbot for …
> POST Campaign Message middleware + timeout check

- .gitignore
- lib/helpers.js
- package.json
- test/lib/helpers.test.js
Refactored the `isYesResponse` method in our `lib/helpers` file.
Adds test for `isYesResponse`.
- Install locally
- Make sure your GAMBIT_YES_RESPONSES env variable is populated with the latest accepted responses in production
- Run `npm run all-tests`
- All tests should pass
Accepted responses that where longer than 1 word were being ignored, example: "i can, hell yea", this change fixes that.
Fixes #866
> Issue 866/multi word yes responses

- app/routes/chatbot.js
- lib/helpers.js
- test/lib/helpers.test.js
Trims data we send for Reportback `caption` and `why_participated` to avoid Phoenix API errors (which result in Gambit returning an error response)
Fire up Lorem Ipsum generator and send through values for `caption` and `why_participated` that exceed 255 characters, verify reportback is successfully submitted (and long values are trimmed)
I'm having trouble finding the exact limit of `why_participated`. [The `length` value defined as `'2048'` for the `why_participated` field with type `'text'` in Phoenix doesn't seem correct](https://github.com/DoSomething/phoenix/blob/28d1ed6a5b8c8031c54f96244daee257c0e6398c/lib/modules/dosomething/dosomething_reportback/dosomething_reportback.install#L60), as I was able to pass a `why_participated` with 2049 characters (`'2048'` probably shouldn't be a …
> Trim Reportback text to avoid Phoenix API errors

- app/routes/chatbot.js
- app/routes/index.js
- documentation/endpoints/chatbot.md
* Only tracks an incoming message (and an outgoing message of `broadcast` if incoming message is responding to a broadcast) for the first Blink attempt, fixing the count of incoming messages in Dashbot analytics.
* Post locally to `chatbot` and include a `x-blink-retry-count` of 1 or more in the headers. 
* Verify Dashbot analytics are not sent for the incoming messages
* Verify Dashbot analytics are sent when the ``x-blink-retry-count` header is removed
Fixes #897
> Check Retry Count before logging incoming messages

- app/routes/chatbot.js
- config/contentful.js
- lib/helpers.js
- package.json
- test/stubs/contentful/all-campaign-fields.json
When a POST Signup or Reportback request fails with status 500:
* Sends a new message type, `error_occurred`, to the end user and places them into Agent View
* Sets the response `x-blink-retry-suppress` to `true` 
Strips emoji from reportback text to fix #907 
Upon staging deploy, text an emoji for a caption and verify that
* Error Occurred Message is sent
* Blink does not retry
Need to update Contentful tests. Opening now to test on staging.
Fixes #902, #907
> Send Error Message and suppress Blink retries on failed Phoenix POST request

- Procfile
Fine tunes the GC to limit the amount of memory storage to match the Standard dyno Mem limit:
https://devcenter.heroku.com/articles/node-memory-use#tuning-the-garbage-collector
- 👀
> Fine tuning gambit's garbage collection

- app/models/BotRequest.js
- app/models/User.js
- app/routes/signups.js
- lib/conversation/replies.js
- lib/helpers.js
* Refactors `User.setOutboundTemplate(messageTemplate)` as `User.updateConversation(messageTemplate, campaignId)`, setting the User:
* Last Outbound Template -- The last message template the User received
* Current Campaign
* Signup Status -- a new property, set to `'doing'` by default if a `campaignId` is passed. As we look to handle more responses than just "Yes" an Ask Signup Message, we'll want to save values like `'ask_signup'` or `'declined_signup'` here to determine how to reply.
* DRY - Refactor the `signups` router to use `lib/conversations/replies` for External Signup Menu Message delivery.  This route was missed in #932 
* Rename  `helpers.renderMessageForMessageType` as `helpers.renderMessageTemplate` for better readability, as ideally all references to `messageType` should …
> User.updateConversation

- app/routes/campaigns.js
- app/routes/signups.js
- config/middleware/campaigns/required-params.js
- config/middleware/signups/required-params.js
* Adds the middleware and required config to the `/signups` route to for quick wins on DRY and increased test coverage.
* Verify a 422 is returned if an `id` or `source` is not included in the body of a POST`/signups` request.
This got me thinking about a bigger refactor to `signups` to share more middleware with `chatbot`, although it'd need some tweaking and would require a bit more work (and review), so keeping this PR bite (byte?) size for now.
* For the `user-get`, we'd need to:
* Read the `identifier` field from a config, as well as the value to query for (`chatbot` queries by User `mobile`, `signups` queries by User`id`)
* Separate middleware for `chatbot` to load the User's Current Campaign if a `req.campaignId` doesn't exist
* Separate middleware for `chatbot` to post the inbound …
> Adds required-params middleware to POST signups, campaigns

- app/routes/index.js
- app/routes/receive-message.js
- config/middleware/receive-message/map-request-params.js
- config/middleware/receive-message/required-params.js
- documentation/README.md
- documentation/endpoints/receive-message.md
- lib/conversation/actions.js
- lib/middleware/map-request-params.js
- lib/middleware/receive-message.js
Adds a **POST** `/receive-message` endpoint that acts like **POST** `/chatbot`, with a few differences:
* It expects a `campaignId` parameter to determine which Campaign to create a Signup for (or to save Signup data against, e.g. quantity, photo)
* It doesn't post to Mobile Commons to send the Gambit reply back to the User-- sending the reply will be the responsibility of the Conversations resource that posts here  https://github.com/DoSomething/gambit-conversations/issues/59
Post locally to `/receive-message` to verify Signup + Campaign Completion steps.
```
curl -X "POST" "http://localhost:5000/v1/receive-message" \
-H "x-gambit-api-key: [apiKey]" \
-H "Content-Type: application/x-www-form-urlencoded; charset=utf-8" \
--data-urlencode "phone=[yourPhoneNumber]" \
--data-urlencode …
```
> Receive Message endpoint

- app/routes/receive-message.js
- config/middleware/receive-message/map-request-params.js
- lib/middleware/map-request-params.js
- lib/middleware/receive-message.js
- lib/middleware/user-get.js
* Adds a `campaignId` to  `config/middleware/receive-message/map-request-params`
* Refactors `lib/middleware/map-request-params` to call async parsers only when `req.client` is Mobile Commons. This is what was causing https://github.com/DoSomething/gambit/pull/944#discussion_r132808228.
* Deletes now deprecated `lib/middleware/receive-message`
Post to `/receive-message` and pass different values for `campaignId`. Verify the reply message returned is for your User's Signup for the Campaign you passed 
Coming soon: Consolebot Campaign ID arg to test **POST** `/receive-message` instead of **POST** `/chatbot` via terminal
> Deprecate middleware/receive-message

- lib/conversation/actions.js
- test/lib/conversation/actions.test.js
Changes the logic for when to post to Mobile Commons by checking when `args.req.client ===  'gambit-campaigns'`. #944 introduced a bug that prevented the Quicksilver POST `/signups` request from delivering External Signup Confirmation messages by posting to Mobile Commons (hotfixed in #947).
You can test locally by using your phone number and sending a POST request to local endpoints:
* `/chatbot` -- Should send text to your number (via Mobile Commons)
* `/receive-message` - Should NOT receive text
* `/signups` -- Should send text to your number. [Can find the Signup `id` to pass](https://github.com/DoSomething/gambit/blob/develop/documentation/endpoints/signups.md) from the logs in your Chatbot request.
> Fixes Conversation Action check for POST Signups

- test/lib/conversation/actions.test.js
- test/utils/stubs.js
Adds test coverage for when Conversation Actions should call `req.user.postMobileCommonsProfileUpdate` 
`npm run all-tests`
#947, #948
> Adds conversation/actions test

- config/lib/contentful.js
- documentation/endpoints/chatbot.md
- documentation/endpoints/receive-message.md
- lib/contentful.js
- lib/conversation/replies.js
- lib/helpers.js
- test/lib/contentful.test.js
Includes a `template` property to the responses of `POST /chatbot` and `POST /receive-message`, returning the name of the Contentful Campaign field used for the reply message text. 
* 👀 
* Post locally `/receive-message` or `/chatbot` to verify non-breakage
Fixes #955
> Include template in POST /receive-message

- app/routes/campaigns.js
- config/lib/contentful.js
- documentation/endpoints/campaigns.md
- lib/contentful.js
- test/lib/contentful.test.js
- test/utils/stubs.js
* Renames the `data.messages` property as `data.templates`
* Removes the `Message` suffix from the values returned, to improve data readability 
* Verify `GET /campaigns/:id` returns `data.templates` without a `Message` suffix
* Sanity check that `POST /chatbot` conversations work as expected
Not renaming the single `renderMessage` functions yet. Ideally we should avoid querying Contentful for each request and re-introduce caching Campaigns to this app to improve performance and fail-proofing.
This will break 2 things that will be quick to change, with PR's coming soon:
* Fixes https://github.com/DoSomething/gambit-conversations/pull/99#issuecomment-327223167
* https://github.com/DoSomething/gambit-conversations/issues/49
> Return data.templates in GET campaigns/:id 

- config/lib/contentful.js
- documentation/endpoints/chatbot.md
- documentation/endpoints/receive-message.md
- lib/contentful.js
- lib/conversation/replies.js
- lib/helpers.js
- test/lib/contentful.test.js
- test/lib/helpers.test.js
- test/utils/stubs.js
* Renames the properties of `config.campaignFields` to return expected values in Gambit Conversations (https://github.com/dosomething/gambit-conversations/issues/49, https://github.com/DoSomething/gambit-conversations/pull/100/)
* Makes corresponding changes for values passed in `lib/conversation/replies` 
* GET /campaigns/:id
* Chatbot conversation
> Rename contentful config.campaignFields properties

- package.json
Edits `package.json` to pin Northstar version instead of pulling the latest `master`. 
In [Northstar JS](https://github.com/DoSomething/northstar-js), I'm debating on whether it's worth casting the Northstar API response into an [object with `camelCase` properties](https://github.com/DoSomething/northstar-js/blob/1.0.0/lib/northstar-user.js), vs just returning the raw API response. If we go that route (or any other potential code-breaking routes), pinning the release prevents breakage.
* https://github.com/DoSomething/northstar-js/issues/35
* https://github.com/DoSomething/northstar-js/issues/33
> Pin Northstar JS dependency to 1.0.0

- app/models/Signup.js
- lib/middleware/signup-create.js
- lib/middleware/signup-get.js
- lib/middleware/user-create.js
- lib/middleware/user-get.js
* Sets a `req.userId` in the User Get and User Create middleware
* Modifies `Signup.lookupCurrent` and `Signup.post` to expect a `userId` string instead of a `user` object.
* This is prep work for #959 - if we pass a `userId` parameter to `POST /receive-message` and set `req.userId`, we can remove the User Get / User Create middleware from Receive Message
* Modifies `Signup.lookupCurrent` and `Signup.post` to expect a `campaignId` number instead of a `campaign` object, to keep consistent with the `userId` change
* Set phone number in Consolebot to a number that doesn't exist for a User (I tend to always use a timestamp, like 201709201232)
* Post a signup , e.g. send `keyword:dunkbot`, to verify a Signup is created
* Continue conversation to verify Signup lookup is working as expected
When …
> Set req.userId

- app/routes/receive-message.js
- config/middleware/receive-message/map-request-params.js
- config/middleware/receive-message/required-params.js
- documentation/endpoints/receive-message.md
- lib/conversation/replies.js
- lib/middleware/validate.js
Now that Gambit Conversations is passing Northstar `userId` parameter when available (https://github.com/DoSomething/gambit-conversations/pull/140), and our Signup methods accept a `userId` string instead of a `user` object (#962), we can remove the Create / Get User middleware from `POST /receive-message` to avoid making double Northstar requests in Gambit Conversations.
Can't deploy this yet because we don't want to break Slack / Consolebot integration in the Conversations API - we'll need to figure out what `userId` to pass over for non phone numbers.
Next up:
Fixes #959
> Receive Message: required userId param

- app/models/User.js
- documentation/endpoints/receive-message.md
- lib/conversation/replies.js
- lib/helpers.js
- package.json
* Adds a Signup object to unblock the final task in https://github.com/DoSomething/gambit-conversations/issues/37: Using the Gambit Conversations cache to return Signup reply messages. When that's in place, a `POST /receive-message` request won't need to GET Phoenix or Contentful Campaigns at all.
* Completes cleanup task in #965, renaming `user.updateConversation` to `update.currentCurrentCampaign`
* Removes User properties no longer used, either from:
* abandoned monolith Gambit+Rivescript approach (`last_outbound_template`, `signup_status`) - #932, #934
* Refactor Phoenix posts (`phoenix_id`) - #941
* DonorsChooseBot (`first_name`, `email`)
* Was never used (`'role`)
Will need to update Conversations API to return the Gambit Campaigns response body `data.reply.text` instead of …
> Include Signup in a POST /receive-message response

- lib/helpers.js
Leftover from #968 - use the new `invalidCaption` and `invalidWhyParticipated` Contentful fields instead of resending `askCaption` and `askWhyParticipated` with a hardcoded prefix.
Run Consolebot, test sending both invalid and valid caption/why values.
Sure, we're deprecating the `POST /chatbot` route soon, but it's lame UX that the current invalid caption reads as:
> Sorry I didn't understand that.
> 
> Got it! Now text back a caption for your photo (think Instagram)! Keep it short & sweet, under 60 characters please.
Seemed worth making the quick fix while we're still running conversations via `POST /chatbot` this next month.
#968
> Use new invalidCaption and invalidWhyParticipated fields

- .env.example
- app/models/Signup.js
- config/lib/rogue.js
- lib/helpers.js
- lib/middleware/signup-create.js
- lib/phoenix.js
- lib/rogue.js
Starts on Rogue integration, posting Signups to Rogue instead of Phoenix if `DS_ROGUE_ENABLED` config var is set to true.
Set `DS_ROGUE_ENABLED` to `true` and add the relevant config variables for Base URI and API Key. Use consolebot to test signups for a new phone number to verify Signups are created.
Set `DS_ROGUE_ENABLED` to `false` -- verify Signup is posted to Phoenix. this is currently not working on Thor (we get the "API response is false" error -- #devops issue)
Once this is deployed to production and works beautifully, we can remove the conditional posting to Phoenix and always post to Rogue, to keep code simpler.
Next up: posting Reportbacks
Because we're looking to get this in for testing with TSG, haven't added test coverage yet. 🤦‍♂️ 👎 
First task in #970
> Post Signups to Rogue

- app/models/Signup.js
- config/lib/rogue.js
- lib/phoenix.js
- lib/rogue.js
Removes code for posting a Signup to the Phoenix API.
Send keyword for User who hasn't signed up and confirm signup is created.
#974
> Remove Phoenix POST Signup

- app/models/Signup.js
- config/lib/rogue.js
- lib/helpers.js
- lib/middleware/draft-completed.js
- lib/rogue.js
- package.json
* Posts a completed Reportback Submission to Rogue Posts endpoint instead of Phoenix Signups.
* Requires passing a Base64 file string of the Reportback image
* Renames `rogue.postSignupForReq` (introduced in #974) to `rogue.createSignupForReq`, so our Reportback function can be called `rogue.createPostForReq` instead of `rogue.postPostForReq`
Complete a campaign via Consolebot, or staging upon deploy.
Up next: 
* Remove Emoji Strip, #971 
* Fetch current Signup from Rogue instead of Phoenix (third task in #970)
Second task in #970
> Post Reportbacks to Rogue

- config/lib/contentful.js
- config/middleware/receive-message/map-request-params.js
- lib/conversation/replies.js
- lib/helpers.js
- lib/middleware/draft-completed.js
- lib/middleware/map-request-params.js
- lib/middleware/signup-create.js
- package.json
- test/lib/helpers.test.js
- test/lib/middleware/map-request-params.test.js
Removes the emoji strip package, and corresponding `helpers.handlePhoenixPostError`, `replies. renderEndConversationWithErrorMsg`  functions that we added to strip emoji in #912, #913 
Post emojis! Although they're showing up as ???'s in Rogue per https://dosomething.slack.com/archives/C0YGXUE01/p1507739954000299
Now that we're no longer posting to the Phoenix proxy in #976, we no longer need to check for the cryptic [`'API response is false'` returned from Phoenix JS](https://github.com/DoSomething/phoenix-js/blob/f086c979cb1cba351512ea83e8450fd25a6cafa4/lib/phoenix-endpoint.js#L103).
Once #976 is merged, I'll update this PR to merge into `develop` instead of the `reportback` branch.
#970
> Remove Emoji Strip, Error Occurred template

- app/models/Signup.js
- lib/middleware/signup-get.js
- lib/rogue.js
- test/lib/middleware/signup-get.test.js
Refactors the Phoenix `GET /signups` request to Rogue `GET /activity`
This PR is to merge into the `issue-971` branch, will update to `develop` once #977 is merged.
* Consolebot: Signup, reportback, repeat for a different Campaign.
* `POST /signups` with valid Signup ID (signup message is sent), invalid Signup ID's (404 is returned)
Farewell, Phoenix Ashes proxy 👋 
Fixes #970
> Fetch Signups from Rogue

- lib/contentful.js
Fixes #981: A bug introduced by the `config.campaignFields` naming changes in #958, where the `response.data.templates` of a `GET /campaigns/:id` request doesn't include any Campaign overrides, only returns rendered templates of the default Contentful Campaign (`campaignID=default`)
Verify the `gambitSignupMenu` template is overridden in http://ds-mdata-responder-staging.herokuapp.com/v1/campaigns/7
Fixes #981
> GET /campaigns/:id override fix

- .env.example
- config/lib/phoenix.js
- lib/phoenix.js
- lib/rogue.js
- package.json
- test/lib/phoenix.test.js
- test/stubs/phoenix/campaign.json
- test/utils/stubs.js
Refactors `lib/phoenix` to use `superagent` to make GET requests, instead using the [Phoenix JS](https://github.com/dosomething/phoenix-js) package. This repo is the only live project that uses Phoenix JS, it's easier maintain and debug when the code lives in the repo itself.
* Removes Phoenix auth credentials from `.env.example`- not needed now that #970 is live
* Starts on tests, doesn't add unit tests for `parsePhoenixCampaign` or `parsePhoenixError` for sake of keeping this PR easier to review
Sanity check a few `POST /chatbot`, `GET /campaigns`, and `GET /campaigns/:id` requests to verify a Campaign is still fetched from the Phoenix API.
When we get around to #983, we'll want to use the Phoenix `GET /campaigns?ids=` index query to retrieve multiple Phoenix Campaigns instead of making …
> Deprecates Phoenix JS

- lib/phoenix.js
Adds the `campaignId` to a Phoenix `GET /campaigns/:id` request to make it easier to fix Contentful keyword misconfigurations (#980)
Real fix will be to exclude any Contentful keywords that don't have matching Phoenix Campaigns, to be handled by #983
> Display campaignId in Phoenix API errors

- lib/helpers.js
- test/lib/helpers.test.js
* Fixes the keyword variable in `helpers.replacePhoenixCampaignVars` per changes in #986
* Removes code we never ended up implementing (render the user's signup keyword if they signed up via keyword). 
In Consolebot, make sure you're signed up for a Campaign and send the Q keyword. Verify you receive the support message with the Campaign keyword rendered.
> Fix keyword replacement per #986

- app/routes/campaigns-single.js
- app/routes/campaigns.js
- app/routes/index.js
- lib/middleware/campaigns-single/contentful-campaigns.js
- lib/middleware/campaigns-single/contentful-keywords.js
- lib/middleware/campaigns-single/phoenix-campaign.js
Splits out the `fetchCampaign` function defined in `app/routes/campaigns` into middleware.
Make GET requests for various Campaign Id's (ones that exist, ones that don't)
* Removes the Contentful URI for now, which is only used internally by the Gambit Slackbot.
* Nice to refactor: Make a single request to the Contentful API to get both the default Campaign and the target Campaign, instead of 2 separate Contentful requests
Fixes #983
> GET /campaigns/:id middleware

- app/routes/campaigns-single.js
- lib/contentful.js
- lib/contentfulQueryBuilder.js
- lib/helpers.js
- lib/middleware/campaigns-single/contentful-campaigns.js
- lib/middleware/campaigns-single/phoenix-campaign.js
- lib/middleware/campaigns-single/render-templates.js
- test/lib/contentful.test.js
- test/lib/helpers.test.js
- test/stubs/contentful/get-entries-campaign.json
Resolves #990 by always returning a response regardless of whether a Phoenix Campaign has a corresponding Contentful campaign. If it doesn't have a Contentful Campaign, we return the `templates` property rendered with the default Contentful Campaign data.
I can deploy to GamCam Staging to confirm expected behavior for both the `GET /campaigns/:id` and `POST /chatbot` endpoints, and that we stop seeing the errors in #990 from web signups on Campaigns without keywords -- but this breaks a bunch of tests, which is why it's not ready to merge just yet. It might be easier to review at this point, as it'd just be less lines of code to review... 
Next up in this branch:
* removing or preferably fixing failing tests
* Improving documentation for endpoints:
* `GET /campaigns` - Returns all Phoenix …
> WIP: Always return GET /campaigns/:id response if Phoenix Campaign ID exists

- config/index.js
- config/redis.js
- server.js
It removes the app.listen binding from inside the redisClient `ready`. This event fires every time the redisClient reconnects and it's ready. The redisClient reconnects when it has been idle for more than the allowed time (60s).
- Follow README to have Redis working in localhost.
- Run `redis-cli`.
- Inside the Redis CLI shell, run `CONFIG SET TIMEOUT 60`. This will set your Redis instance to disconnect clients after 60 seconds.
- Run `heroku local` in a different tab.
- Every 60 seconds of idling time, you should see a `debug: redisClient is reconnecting` log message.
This PR fixes this error:
```
2017-11-01T13:13:00.978604+00:00 app[web.4]: events.js:160
2017-11-01T13:13:00.978607+00:00 app[web.4]:       throw er; // Unhandled 'error' event
2017-11-01T13:13:00.978608+00:00 app[web.4]: …
```
> Fixes the bug of listening to ready event to bind the app

- .env.example
- app/models/Signup.js
- lib/helpers.js
- test/lib/helpers.test.js
* Removes deprecated `helpers` functions and their tests
* Adds tests for `helpers.sendResponseForSignup`
* Refactors `helpers.formatSignupResponse(signupDoc)` as a Signup instance method 
Verify all POST and GET requests work as expected. Will deploy to staging to confirm via Conversations.
Next up:
- Add tests for `Signup` model
- Move `generatePassword` helper and test into Gambit Conversations
#989
> TGM: Helpers cleanup

- README.md
- config/logger.js
- package.json
* Changes Github URL's to `gambit-campaigns` - closes #942 
* Removes Winston MongoDB, I don't think I've ever queried this - it was added from the legacy days. Logstash should deprecate?
👀 
Ideally our logger should be refactored in the future, to DRY Gambit Conversations and Blink sharing the same Request Id's (#900, https://github.com/DoSomething/gambit-conversations/pull/228)
Fixes #989
> Rename repo + remove Winston MongoDB

- config/lib/helpers/reportback.js
- lib/helpers.js
- lib/helpers/reportback.js
- lib/middleware/receive-message/draft-caption.js
- lib/middleware/receive-message/draft-quantity.js
- lib/middleware/receive-message/draft-why-participated.js
- test/lib/helpers.test.js
- test/lib/lib-helpers/reportback.test.js
- test/utils/stubs.js
- Refactors reportback specific methods out of the `helpers.js` file into its own helper `/helpers/reportback.js`.
- Makes decimal reportback quantities invalid.
It will round up/down based on decimal quantity remainder when a valid Numeric quantity is received.
- 👀 
- Run `npm run all-tests`
Task 1 - https://github.com/DoSomething/gambit-campaigns/issues/1012
> Invalidates decimal reportback quantities.

- lib/phoenix.js
Allows non english campaigns to be properly rendered in the `/campaigns` route.
- 👀 
- `http://ds-mdata-responder-staging.herokuapp.com/v1/campaigns/7177` should return the correct campaign info.
what else?
Slack thread: https://dosomething.slack.com/archives/C4VN7J0SE/p1514485870000401
> fix non en language campaigns

- .env.example
- config/lib/helpers/campaign.js
- config/lib/phoenix.js
- lib/helpers.js
- lib/helpers/campaign.js
- lib/phoenix.js
- package-lock.json
- package.json
- test/lib/helpers.test.js
- test/lib/lib-helpers/campaign.test.js
- test/lib/phoenix.test.js
- test/stubs/phoenix/ashes-campaign.json
- test/stubs/phoenix/campaign.json
- test/utils/stubs.js
This PR takes a stab at changing the Phoenix API from old (PA) to new (PN), and seems to find a blocker. The index `GET /campaigns` resource Gambit uses to get a list of Campaigns by given `ids` query parameter doesn't exist. As a workaround, this PR makes multiple requests for each Campaign -- but it seems awfully slow on localhost. We may need to significantly refactor how we manage the list of active Campaigns, or per [Slack comment](https://dosomething.slack.com/archives/C3ASB4204/p1521047195000687?thread_ts=1521038744.000837&cid=C3ASB4204) from @DFurnes, get that [GraphQL](https://github.com/dosomething/graphql) in:
>  I'd go with multiple requests (or see about getting this into GraphQL) so we can more easily cache individual resources.
Update your `DS_PHOENIX_API_BASEURI` to the …
> Support Ashes and Phoenix URLs via config 

- config/lib/helpers/cache.js
- config/lib/phoenix.js
- lib/helpers.js
- lib/helpers/cache.js
- lib/phoenix.js
- test/lib/helpers.test.js
Extracts the Redis Cacheman into a cache helper. Also removes `findAndReplaceKeywordVarForCampaignId` deprecated by #1022.
Flush cache and verify expected behavior from GET Campaigns requests.
Tests coming up in the next PR, needed to update eslint.
> Cache helper

- .eslintrc
- app/exceptions/ClosedCampaignError.js
- app/exceptions/UnprocessibleEntityError.js
- lib/contentful.js
- lib/middleware/timeouts.js
- lib/tools/profiler.js
- lib/tools/uploader.js
- package-lock.json
- package.json
- test/lib/contentful.test.js
- test/lib/lib-helpers/cache.test.js
Adds a test for the cache helper in #1024, which is essentially a copy/paste job from [Conversations](https://github.com/DoSomething/gambit-conversations/blob/2.4.1/lib/helpers/cache.js).
Our linter wasn't happy with the use of `rewire`, complaining about a [`TypeError: Assignment to constant variable.`](https://github.com/jhnns/rewire/issues/79). Updating our lint config to match Conversations made it happy, and required some cleanup in other files.
`npm run all-tests`
Once #1024 is merged, I'll edit this PR to merge into `master` instead of `cleanup/cache`.
> Cache helper test + eslint update

- config/lib/helpers/botConfig.js
- lib/contentful.js
- lib/helpers.js
- lib/helpers/botConfig.js
- lib/helpers/campaign.js
- lib/helpers/index.js
- lib/middleware/campaigns-index/phoenix-campaigns.js
- lib/middleware/campaigns-single/contentful-keywords.js
- lib/middleware/campaigns-single/phoenix-campaign.js
- lib/phoenix.js
- test/lib/phoenix.test.js
Starts on renaming and refactoring a Phoenix campaign's corresponding Gambini campaign entry as `botConfig` property on the campaign.  Our Gambini Contentful data will eventually be migrated and sourced from Phoenix.
* Adds a botConfig helper with a `parsePostTypeFromBotConfig` function to return the botConfig's post type, either `'text'` or `'photo'`. 
* Adds functions to the campaign helper to get and fetch campaigns, extracting the cache logic out of the Phoenix helper (see #1024). Our source of campaigns could potentially change one day, e.g. [GraphQL](https://github.com/dosomething/graphqll) 
* For now, adds an extra call to Contentful to set the `req.campaign.botConfig` -- but that'd be silly to ship to production. What I should have done was stopped here, feature flagged this, and …
> botConfig - part 1 [pr]

- app/routes/receive-message.js
- lib/helpers/campaignActivity.js
- lib/helpers/index.js
- lib/helpers/request.js
- lib/middleware/receive-message/map-request-params.js
- lib/middleware/receive-message/text-post.js
- lib/rogue.js
- test/lib/lib-helpers/campaignActivity.test.js
- test/lib/lib-helpers/request.test.js
- test/lib/middleware/receive-message/text-post.test.js
- test/utils/stubs.js
Adds new middleware to the `receive-message` to handle Text Post conversations if a post type of `text` has been passed from Conversations.
Upon staging deploy, text the LUCKYBOT keyword to join Get Lucky. I've updated its [botConfig](https://gambit-admin-staging.herokuapp.com/campaigns/2900) for text posts.
* Need to investigate, but I don't seem to see any texts posts created in Rogue. The HTTP response suggests a `photo` post is created, although this branch should be passing `'text'`  as the `type` parameter.
* Using the Contentful campaign fields `askCaption` and `invalidCaption` as replies for now. TODO Use the textPostTemplate fields defined on the campaign `postTemplate` reference.
* #1021 
* This unblocks starting on https://github.com/DoSomething/gambit-conversations/issues/304
> Text Post middleware [pr]

- config/lib/helpers/botConfig.js
- lib/contentful.js
- lib/helpers/botConfig.js
- lib/middleware/campaignActivity/text/post-create.js
- lib/middleware/campaigns/single/bot-config-parse.js
- lib/replies.js
- test/lib/contentful.test.js
- test/lib/lib-helpers/botConfig.test.js
- test/lib/middleware/campaignActivity/text/post-create.test.js
- test/lib/middleware/campaigns/single/bot-config-parse.test.js
- test/utils/stubs.js
Returns the field values from a botConfig's `postConfig` entry as properties in the `templates` object of a `GET /campaigns/:id` response.
Contentful changes:
*  [x] Added a new `photoPostConfig` content type, with `photoPost` fields like `gambitSignupMenuMessage`, `askQuantityMessage`
<br>
After go live:
Gambit changes:
* Renames the botConfig `config.templates` as `config.templatesByContentType`, adds `textPostConfig` and `photoPostConfig` properties (#1032) per Contentful changes above 👆 
* Refactors the `botConfig` helper to gather templates based on content type
* Adds new `askText` and `invalidText` replies for use in Text Post middleware
Upon staging deploy:
* Verify textPost conversation flow (LUCKYBOT)
* Verify photoPost conversation flow (BOOKBOT)
#1021
> textPostConfig and photoPostConfig templates [pr]

- app/routes/campaignActivity.js
- config/lib/helpers/botConfig.js
- lib/helpers/request.js
- lib/middleware/campaignActivity/external/index.js
- lib/replies.js
- test/lib/lib-helpers/request.test.js
- test/lib/middleware/campaignActivity/external/index.test.js
Adds support for a new `externalPostConfig` content type that can be saved to a botConfig's `postConfig` reference field.
* I've manually created the content type in Contentful, and added it as an available entry to select in the campaign `postConfig` reference field settings.
I've edited BOOKBOT (campaign 2299) on staging to reference a new `externalPostConfig` entry. Upon staging deploy, verify:
* A [`GET /campaigns/2299` response](https://ds-mdata-responder-staging.herokuapp.com/v1/campaigns/2299) returns a `postType` of `'external'`, and contains `startExternalPost`, `webStartExternalPost`, and `startExternalPostAutoReply` templates
* In tandem with https://github.com/DoSomething/gambit-conversations/pull/321, verify texting BOOKBOT enters a campaign conversation that creates a signup …
> External Posts

- lib/helpers/campaignActivity.js
- lib/helpers/request.js
- lib/middleware/campaignActivity/photo/draft-caption.js
- lib/middleware/campaignActivity/photo/draft-why-participated.js
- lib/middleware/campaignActivity/signup-create.js
- lib/middleware/campaignActivity/signup-get.js
- test/lib/lib-helpers/campaignActivity.test.js
- test/lib/lib-helpers/request.test.js
- test/lib/middleware/campaignActivity/signup-get.test.js
- test/utils/factories/reportbackSubmission.js
Adds new campaignActivity helpers for saving a draft caption and whyParticipated, slowly chipping away at adding unit test coverage for `lib/middleware/campaignActivity/photo`, using the `helpers.request.isValidReportbackText` introduced in #1029.
* Adds request helpers `setSignup` and `setDraftSubmission`, following conventions used in the [Conversations request helper](https://github.com/DoSomething/gambit-conversations/blob/2.5.6/lib/helpers/request.js#L19).
* Adds campaignActivity helper function `getReportbackTextFromReq`, with comment to document why we trim reportback text, refs [Slack conversation in #gambit 
](https://dosomething.slack.com/archives/C1V0M6RPE/p1523558690000067)
Verify the first and second photo post for a campaign work as expected (1st post should collect …
> Caption + Why Participated campaignActivity helpers [pr]

- lib/middleware/campaignActivity/photo/draft-not-found.js
- test/lib/middleware/campaignActivity/photo/draft-not-found.test.js
Replaces check for deprecated `req.askNextQuestion` check with a call to `helpers.request.shouldAskNextQuestion` in the Photo Post Draft Not Found middleware.
Complete a photo post, and text in the keyword (e.g. MIRROR). Verify the `completedPhotoPost` template is sent.
Fixes #1047
> Fixes reply when keyword sent for completed photo post

- lib/contentful.js
- lib/helpers/defaultTopicTrigger.js
- test/lib/contentful.test.js
- test/utils/stubs.js
* Restores using the Contentful client `getEntries` to fetch a single entry, and documents why to use instead of `getEntry` - (refs #1048).  The `campaign` reference entry wasn't available in a `GET /topics/:id` request when fetching the topic entry.
* Removes functions that reference the `campaign.postConfig` reference field -- this is no longer used and should be deleted from the `campaign` content type. Campaigns are linked to topics via the topic entry's `campaign` reference field.
Verify that `GET /campaigns/:id` and `GET topics/:id` return expected data.
> Contentful cleanup

- lib/helpers.js
- lib/helpers/topic.js
Modifies parsing the response of a `GET /topics/id` request to return a `templates` property, even if the topic doesn't have a `campaign` reference set.
* Adds check for when the `campaignId` field on a `campaign` entry doesn't exist in Phoenix, which is currently happening on `GET /v1/topics/5fpmfk4ETe4ss6qogEcGSi`
* 👀
* Set env vars to Contentful Preview API and verify `GET v1/topics` and `GET /v1/topics/5fpmfk4ETe4ss6qogEcGSi` return success responses
Preview API is fun because Contentful creates an ID as soon as an editor opens the form to create a new entry. I ran into this error when working on https://github.com/DoSomething/gambit-conversations/pull/328 per continuing https://github.com/DoSomething/gambit-conversations/pull/336
> Return templates when topic doesn't have a campaign

- app/routes/broadcasts/index.js
- app/routes/broadcasts/single.js
- app/routes/index.js
- config/lib/helpers/broadcast.js
- config/lib/helpers/cache.js
- documentation/README.md
- lib/contentful.js
- lib/contentfulQueryBuilder.js
- lib/helpers/broadcast.js
- lib/helpers/cache.js
- lib/helpers/index.js
- lib/middleware/broadcasts/index/broadcasts-get.js
- lib/middleware/broadcasts/single/broadcast-get.js
- test/lib/contentful.test.js
- test/lib/lib-helpers/broadcast.test.js
- test/utils/factories/broadcast.js
- test/utils/factories/contentful/broadcast.js
- test/utils/stubs.js
Adds `GET /v1/broadcasts` and `GET /v1/broadcasts/:id` endpoints to fetch and parse `broadcast` entries in Contentful, caching entries for the single view. This is essentially moving the code out of [gambit-conversations ](https://github.com/dosomething/gambit-conversations) and into this repo, allowing us to consolidate Contentful queries (and caching them in Redis)
Part 2 will include the following (excluded to help keep this reviewable):
* Parsing the `attachments` Media field on the `broadcast 
* Documentation, example requests & responses
* Unit tests for middleware, integration tests for routes
Verify the `GET /broadcasts` and `GET broadcasts/:id` responses look as expected.
Feels appropriate to rename this repo as `gambit-content` once we remove all references to Contentful from …
> Broadcasts endpoint - part 1

- app/routes/index.js
- lib/contentful.js
- lib/helpers/broadcast.js
- test/lib/contentful.test.js
- test/lib/lib-helpers/broadcast.test.js
- test/lib/middleware/broadcasts/index/broadcasts-get.test.js
- test/lib/middleware/broadcasts/single/broadcast-get.test.js
- test/utils/factories/contentful/broadcast.js
- test/utils/stubs.js
Continues part 1 (#1059):
- Returns broadcast media in the `message.attachments` property, porting over [code from Conversations](https://github.com/DoSomething/gambit-conversations/blob/2.12.3/lib/contentful.js#L139)
- Adds tests for `lib/middleware/broadcasts`
- Fixes epic bug in  `GET /campaigns/:id` response introduced by #1059 
- Verify `72mon4jUeQOaokEIkQMaoa` contains `message.attachments`
- Verify GET /campaigns/:id returns a single campaign
Last items left for this PR or part 3:
- Add docs
- Add integration tests
https://www.pivotaltracker.com/story/show/154737123
> Broadcasts endpoint - part 2

- documentation/README.md
- documentation/endpoints/broadcasts.md
- documentation/endpoints/topics.md
- lib/contentful.js
- lib/contentfulQueryBuilder.js
- lib/helpers/broadcast.js
- lib/helpers/defaultTopicTrigger.js
- lib/helpers/index.js
- lib/helpers/response.js
- lib/helpers/topic.js
- lib/helpers/util.js
- lib/middleware/broadcasts/index/broadcasts-get.js
- lib/middleware/broadcasts/single/broadcast-get.js
- lib/middleware/campaigns/index/response.js
- lib/middleware/campaigns/single/response.js
- lib/middleware/defaultTopicTriggers/index/defaultTopicTriggers-get.js
- lib/middleware/topics/index/topics-get.js
- lib/middleware/topics/single/topic-get.js
- test/lib/contentful.test.js
- test/lib/lib-helpers/broadcast.test.js
- test/lib/lib-helpers/defaultTopicTrigger.test.js
- test/lib/lib-helpers/response.test.js
- test/lib/lib-helpers/topic.test.js
- test/lib/lib-helpers/util.test.js
- test/lib/middleware/broadcasts/index/broadcasts-get.test.js
- test/lib/middleware/defaultTopicTriggers/index/defaultTopicTriggers-get.test.js
- test/lib/middleware/topics/index/topics-get.test.js
- test/utils/stubs.js
Adds a `meta` object property to the result in addition to the `data` array property for all index endpoints
* Adds support for a `skip` query parameter to `GET /broadcasts` and `GET /topics`.
* No longer caches the `GET /topics` index query per https://github.com/DoSomething/gambit-conversations/pull/371. Eventually we'll accumulate enough topics that we'll want to page through results... caching pages of results isn't required and adds additional complexity for something we don't need.
Verify that passing `skip` query parameters to the `GET /broadcasts` and `GET /topics` endpoints.
We still need a cached list of all topics to easily find topics by campaign.. but ideally this should get refactored by creating separate `contentful.fetch` functions to make Contentful queries that find …
> Adds meta property into index query result [pr]

- config/lib/helpers/util.js
- documentation/endpoints/broadcasts.md
- documentation/endpoints/topics.md
- lib/contentful.js
- lib/contentfulQueryBuilder.js
- lib/helpers/util.js
- test/lib/contentful.test.js
- test/lib/lib-helpers/util.test.js
Adds support for a `limit` query parameter.
Verify limit parameter limits the number of results returned.
We'll need to require authentication for these endpoints, will update Gambit Admin + Conversations accordingly and then open a PR.
Fixes pagination bug in https://github.com/DoSomething/gambit-admin/pull/64
> Adds a limit query parameter for Contentful index queries 

- app/routes/contentfulEntries/single.js
- app/routes/index.js
- config/lib/helpers/broadcast.js
- config/lib/helpers/defaultTopicTrigger.js
- config/lib/helpers/topic.js
- documentation/README.md
- documentation/endpoints/broadcasts.md
- documentation/endpoints/topics.md
- lib/contentful.js
- lib/helpers/broadcast.js
- lib/helpers/contentfulEntry.js
- lib/helpers/defaultTopicTrigger.js
- lib/helpers/index.js
- lib/helpers/topic.js
- lib/middleware/contentfulEntries/single/contentfulEntry-get.js
- lib/middleware/topics/single/topic-get.js
- test/lib/lib-helpers/broadcast.test.js
- test/lib/lib-helpers/defaultTopicTrigger.test.js
- test/lib/lib-helpers/topic.test.js
- test/lib/middleware/topics/single/topic-get.test.js
- test/utils/factories/contentful/broadcast.js
A first stab at splitting out our `broadcast` Contentful content type into separate content types taking on 2 of them. We'll pass these Contentful ID to a `POST /messages?origin=broadcast` request as the `broadcastId` -- but Conversations will also save the ID as the conversation topic.  These content types contain a `broadcast` field that references  `message` entries, which we use to send a broadcast message -- but also contain additional fields to return as `templates` for when the user's topic is set to one of these broadcast types.
Deprecates use of the `survey_response` topic broadcasts we currently send.
Fields:
* `name` - text field 
* `broadcast` -the outbound message to send, limited to `message` entries
* `autoReply` - auto reply message to send, also limited to `message` …
> Adds autoReplyBroadcast and askChangeTopicBroadcast types [pr]

- lib/helpers/broadcast.js
- test/lib/lib-helpers/broadcast.test.js
- test/utils/factories/contentful/autoReplyBroadcast.js
- test/utils/factories/contentful/message.js
Adds check for a `broadcast` field in the `parseBroadcastMessageFromContentfulEntryAndTemplateName` broadcast helper function, returning null if it doesn't exist. 
Create a draft `autoReplyBroadcast` entry without any fields. Verify that a `GET /broadcasts` query includes the entry, returning it with a null `message` property.
This field is required, so this error wouldn't happen on production -- but does require us to check for its existence to avoid 500 errors in QA.
Fixes https://dosomething.slack.com/archives/C1V0M6RPE/p1533575475000182
> Fixes bug in GET /broadcasts response for draft entries without a broadcast reference

- config/lib/helpers/contentfulEntry.js
- config/lib/helpers/defaultTopicTrigger.js
- config/lib/helpers/topic.js
- lib/helpers/broadcast.js
- lib/helpers/contentfulEntry.js
- lib/helpers/defaultTopicTrigger.js
- lib/helpers/topic.js
- test/lib/lib-helpers/contentfulEntry.test.js
- test/lib/lib-helpers/defaultTopicTrigger.test.js
- test/lib/lib-helpers/topic.test.js
- test/utils/factories/contentful/autoReply.js
- test/utils/factories/contentful/autoReplyBroadcast.js
Cleanup in anticipation of refactoring `autoReplyBroadcast` per the new `autoReplyBroadcast` and `autoReply` content types. 
* Moves the `config.contentType` definitions for the broadcast, defaultTopicTrigger, and topic helpers into the contentfulEntry helper, as an `askYesNo` can serve as both a broadcast (it's `broadcastable`) and as a topic (it has `templates`)
* Moves the `parseTemplatesFromContentfulEntryAndFieldNames` function out of broadcast helper and into contentfulEntry to be reused by other content types that will use the same pattern of creating a `message` or `changeTopicMessage` reference field and adding it to the `templates` array to render a topic's templates
Spot check types returned:
* `GET /broadcasts` will return `broadcast` and `autoReplyBroadcast` entries
* `GET …
> Consolidate content type helper configs into contentfulEntry config

- config/lib/helpers/contentfulEntry.js
- documentation/endpoints/broadcasts.md
- documentation/endpoints/topics.md
- lib/helpers/broadcast.js
- lib/helpers/contentfulEntry.js
- lib/helpers/topic.js
- test/lib/lib-helpers/broadcast.test.js
- test/lib/lib-helpers/contentfulEntry.test.js
- test/utils/factories/contentful/askYesNo.js
- test/utils/factories/contentful/autoReply.js
- test/utils/factories/contentful/autoReplyBroadcast.js
- test/utils/factories/contentful/broadcast.js
- test/utils/factories/contentful/message.js
- test/utils/stubs.js
This PR adds a `topic` property to the properties in the `templates` object of a `GET /topics/:id` response... and also adds a `topic` property to the `message` object in a `GET /broadcasts/:id`. If said `topic` object contains an `id` property, it means that when a user receives the given template/message, their conversation topic should be updated. In a future PR, [gambit-conversations](https://github.com/dosomething/gambit-conversations) will inspect this topic property and change the `conversation.topic` accordingly if a relevant broadcast/reply is received/sent.
This can be seen in two instances for our new types:
* for an `autoReplyBroadcast`, if the `message.topic` property contains an id -- the conversation topic should be updated upon receiving the broadcast. The …
> Finalizing askYesNo and autoReplyBroadcast template fields [pr]

- config/lib/helpers/contentfulEntry.js
- documentation/endpoints/broadcasts.md
- documentation/endpoints/topics.md
- lib/helpers/contentfulEntry.js
* I've manually created an `askSubscriptionStatus` content type in Contentful, simply with the `text` and `attachments` fields. On the Conversations side, if a broadcast request is sent for an `askSubscriptionStatus` type, we'll hardcode setting the conversation to `askSubscriptionStatus`. 
* Ideally, we'd add `saidActive`, `saidLess`, `needsMoreInfo` templates to avoid hardcoding replies in Rivescript, but we're aiming to send these broadcasts again soon -- and I'm aiming to get us off the legacy `broadcast` type. When we set the `topic` field there we're only using it for `survey_response` broadcasts (which our new `AutoReplyBroadcast` in #1072 will deprecate) and `ask_subscription_status` broadcasts (which this type aims to deprecate)
* Returns a topic summary instead of id per …
> Adds askSubscriptionStatus as a broadcastable content type

- config/lib/helpers/contentfulEntry.js
- config/lib/middleware/campaignActivity/required-params.js
- documentation/endpoints/campaignActivity.md
* Adds two new types I've manually created in Contentful to deprecate using the legacy broadcast type configured with `askText` or `startPhotoPost` template values.
* The `photoPostBroadcast` topic reference field is limited to `photoPostConfig` entries; the `textPostBroadcast` topic reference field is limited to `textPostConfig` entries.
* Updates the `POST /campaignActivity` required params to make `postType` optional - as our `autoReply` topic won't be sending a `postType` but may be sending a request for a signup. 
Verify the API responses look broadcastable (a message.text is provided, the message.template matches the content type name). I've created test entries for each type:
`5t2fmKd2iQgaCCy8Kgg0CI` -a photoPostBroadcast
`1pGaGNh8fCyIeqAukYkUwM` - a textPostBroadcast
```
// …
```
> Adds photoPostBroadcast and textPostBroadcast types

- config/lib/helpers/contentfulEntry.js
- documentation/endpoints/broadcasts.md
- lib/helpers/broadcast.js
- lib/helpers/contentfulEntry.js
- lib/helpers/topic.js
- test/lib/lib-helpers/contentfulEntry.test.js
- test/lib/lib-helpers/topic.test.js
- test/utils/factories/broadcast.js
- test/utils/factories/contentful/askYesNo.js
- test/utils/factories/contentful/autoReply.js
- test/utils/factories/contentful/broadcast.js
- test/utils/factories/contentful/campaign.js
- test/utils/factories/contentful/textPostConfig.js
- test/utils/factories/topic.js
Modifies the contentfulEntry helper `getTopicTemplatesFromContentfulEntry` and `getMessageTemplateFromContentfulEntryAndTemplateName` to set the message or template topic by calling `helpers.topic.getById` instead of the `helpers.contentfulEntry.getSummaryFromContentfulId` -- which doesn't include campaign information (which ideally we'd return to avoid making multiple `GET /topics/:id` requests when processing a user's reply to an outbound `askYesNo`-- when looking up the `askYesNo` topic to find replies, if a user says yes, it's convenient to have the campaign id available for posting campaign activity)
* Verify a full topic object is returned in the `message.topic` properties of a `GET /broadcasts` request for a non askYesNo (e.g. `5t2fmKd2iQgaCCy8Kgg0CI`)
```
// 20180815190247
// …
```
> Return full objects instead of summaries for nested topics in GET topics/broadcasts responses [pr]

- config/lib/helpers/cache.js
- documentation/README.md
- documentation/endpoints/campaignActivity.md
- documentation/endpoints/campaigns.md
- lib/contentful.js
- lib/helpers/cache.js
- lib/helpers/campaign.js
- lib/helpers/contentfulEntry.js
- lib/middleware/campaigns/single/campaign-get.js
- lib/middleware/campaigns/single/topics-get.js
- test/lib/lib-helpers/campaign.test.js
Modifies the `campaign-get` middleware in a `GET /campaigns/:id` response to query Contentful for the `campaign` entry that has a `campaignId` field value matching our campaign id passed in the query parameter, parse it, and set it as a `config` property on the campaign.
* Renders the newly added `webSignup` field as a `config.templates.webSignup` property - returning the text to send a user, and the topic to set the conversation to
* Adds a `campaignConfigs` cache to cache `campaign` Contentful entries
* Adds a `cache` query parameter to the `GET /campaigns/:id` endpoint to allow manually clearing Redis cache for the campaign and campaignConfig
This still needs more unit tests (e.g. `parseCampaignConfig`) but wanted to open at this point to help keep this reviewable)
Verify `GET …
> Adds config.templates to a GET /campaigns/:id response [pr]

- lib/helpers/campaign.js
- test/lib/lib-helpers/campaign.test.js
- test/utils/factories/contentful/campaign.js
Modifies `parseCampaignConfig` to return an empty response if the given campaignId does not have a corresponding `campaign` Gambini entry, preventing returning a 500 error returned from a `GET /campaigns/:id` for the campaignId.
a `GET /campaigns/4` request should return an empty object for the `config` property.
Bug from #1076 -- I rolled back production 5.13.0 to avoid errors for signup message requests for campaigns without configs (refs https://dosomething.slack.com/archives/C1V0M6RPE/p1534796348000100)
Fixes bug in #1076
> Fixes GET /campaigns/:id response when campaign does not have config

- config/lib/helpers/topic.js
- documentation/endpoints/topics.md
- test/lib/lib-helpers/topic.test.js
- test/utils/stubs.js
Follow up to https://github.com/DoSomething/gambit-conversations/pull/389 (and to be deployed to prod once that PR makes it to conversations-prod): 
* removes the `MENU` command reference found in a `declinedContinue` template
*  removes the `askSignup` templates 
* removes `memberSupport` template removed in https://github.com/DoSomething/gambit-conversations/pull/388
Verify the `declinedContinue` template prompts user to text Q instead of MENU. This template can be triggered by joining a campaign topic (e.g. text PUMP), sending a quick reply ("hello"), then sending a catchAll (e.g. France) to the `askContinue` template:
https://www.pivotaltracker.com/story/show/159796050
> Topic templates cleanup

- .github/README.md
- documentation/endpoints/topics.md
* Updates topic type descriptions per [5.12.0](https://github.com/DoSomething/gambit-campaigns/releases/tag/5.12.0)
* Removes reference to Ashes in README missed in #1078 
👀 
Now that the legacy broadcast type is soon to be no longer supported, I'm kinda considering a major version bump and finally renaming this repo as `gambit-content`?
> Documentation updates

- app/routes/contentfulEntries/index.js
- app/routes/index.js
- documentation/README.md
- documentation/endpoints/contentfulEntries.md
- lib/contentful.js
- lib/contentfulQueryBuilder.js
- lib/helpers/campaign.js
- lib/helpers/contentfulEntry.js
- lib/middleware/contentfulEntries/index/contentfulEntries-get.js
- lib/middleware/contentfulEntries/single/contentfulEntry-get.js
- test/lib/contentful.test.js
- test/lib/lib-helpers/campaign.test.js
- test/lib/lib-helpers/contentfulEntry.test.js
- test/lib/middleware/contentfulEntries/index/contentfulEntries-get.test.js
- test/lib/middleware/contentfulEntries/single/contentfulEntry-get.test.js
Adds a `GET /contentfulEntries` endpoint that serves as a proxy to our Contentful API, enabling queries such as finding all `campaign` entries with a `webSignup` reference set, or all `textPostConfig` entries that reference a given `campaign` entry id. 
Each item in the `data` response is an object with a `raw` property set to the Contentful entry, and a `parsed` property if the entry is parsed and returned as a broadcast, topic, or defaultTopicTrigger in the respective endpoints.
Verify `GET /contentfulEntries` works as expected
Once Conversations inspects the `templates.webSignup` in a `GET /campaigns` response to source the signup confirmation message, we'll want Gambit Admin/Slack to query this endpoint to provide a list of all campaigns that currently have webSignup templates …
> Adds GET /contentfulEntries index endpoint

- documentation/endpoints/defaultTopicTriggers.md
- lib/helpers/defaultTopicTrigger.js
- lib/middleware/defaultTopicTriggers/index/defaultTopicTriggers-get.js
- test/lib/middleware/defaultTopicTriggers/index/defaultTopicTriggers-get.test.js
Adds support for a `cache` query param set to `false` to fetch `defaultTopicTrigger` entries directly from Contentful, instead of from the cached `defaultTopicTriggers` cache entry for `all`, unblocking https://github.com/DoSomething/gambit-conversations/pull/398 from reloading Rivescript from Contentful upon the rivescript cache clear.
Verify that a `GET /defaultTopicTriggers?cache=false` request directly queries Contentful, and that excluding the query parameter still returns the cached list if exists (we'll still need this up until we turn on Redis caching in the next upcoming Conversations release)
It'll be great to get rid of all of these cached lists of `defaultTopicTrigger` entries! It's also a part of what happens in #1082 -- a single misconfigured keyword can wipe out all …
> Adds cache query param to GET /defaultTopicTriggers

- lib/helpers/contentfulEntry.js
- test/lib/lib-helpers/contentfulEntry.test.js
Adds a check for existence of a `contentfulEntry` arg in `helpers.contentfulEntry. getMessageTemplateFromContentfulEntryAndTemplateName`. It can be set to null when a draft value is saved, which throws an error in production.
* Edit a test campaign's `webSignup` reference field to a draft entry, ignore the warning and publish. Execute an `GET /campaigns/:id?cache=false` request to verify errors are not thrown. I've been using a random DB campaign id [2299](https://app.contentful.com/spaces/owik07lyerdj/entries/68Oy1FcaR2EiaMieicaoom) to test, but we shouldn't be using any active campaigns we're collecting signups for 😬 
* Sanity check that `GET /topics/:id` returns expected results without any errors.
Getting this in place to avoid any unexpected errors when rolling out the `webSignup` …
> Check for draft webSignup references

- config/lib/helpers/contentfulEntry.js
- lib/helpers/contentfulEntry.js
Exposes entries with the newly askVotingPlanStatus content type created in Contentful as a broadcasts.
👀 , verify a GET `/v1/broadcasts/4LJn0P1LeoUauC0CkESYKE` request looks as expected
Wasn't sure about the async forEach disabling lint approach to find the topic fields that correspond to template fields (e.g. `saidNo` template changes topic to `saidNoTopic`)
First steps for Make A Voting Plan
> Adds askVotingPlanStatus type

- config/lib/helpers/contentfulEntry.js
- documentation/endpoints/topics.md
Changes template names to newly added fields, will manually delete the ones we're removing. 
[GET /broadcasts/4LJn0P1LeoUauC0CkESYKE](https://gambit-admin-staging.herokuapp.com/broadcasts/4LJn0P1LeoUauC0CkESYKE)
> Renames askVotingPlanStatus templates

- documentation/endpoints/topics.md
- lib/middleware/topics/index/topics-get.js
- test/lib/middleware/topics/index/topics-get.test.js
When the redis cache is empty, a `GET /topics` index query will time out with seemingly infinite nested getting/caching queries for campaigns when getting the defaultTopicTriggers for each result item. We eventually recover because the data begins to cache, but this PR simplifies it all by removes the call to get or fetch defaultTopicTriggers entirely during a `GET /topics` request, no longer including a `triggers` property in each result item.
This changes only affects Gambit Admin and it isn't such an issue anymore now that we're revamping the Campaigns page to make individual queries to the `GET /contentfulEntries` endpoint (https://github.com/DoSomething/gambit-admin/pull/76). To avoid building out extra code for custom queries on our end -- I'd prefer we start exposing our Gambit …
> Removes fetching triggers in GET /topics index queries

- config/lib/helpers/contentfulEntry.js
- lib/helpers/contentfulEntry.js
- test/lib/lib-helpers/contentfulEntry.test.js
Continuing part in #1091 -  this PR inspects newly added `yesTransition` and `noTransition` reference fields on the `askYesNo` type to render the `saidYes` and `saidNo` templates. It also supports existing `askYesNo` entries that won't have these fields set, inspecting the `saidYes`, `saidYesTopic`, `saidNo`, `saidNoTopic` field values as a backup.
The draft "Dev test askYesNo" entry has only the transition fields set and does not have the older fields set, should return non-empty `saidYes` and `saidNo` templates.
* https://gambit-admin-staging.herokuapp.com/broadcasts/5q56wA4uJ2SoAi6uAS4uYK
Any other askYesNo won't have the new fields set but should still return non-empty `saidYes` and `saidNo` templates:
*  https://gambit-admin-staging.herokuapp.com/broadcasts/296WVJhHQ8CMsuUyEsGo4s …
> Topic templates cleanup: part 2

- config/lib/helpers/topic.js
Removes deprecated templates, now that Conversations uses the `webSignup` template defined on a campaign config for signup confirmation messages (deployed to prod in https://github.com/DoSomething/gambit-conversations/releases/tag/3.8.0)
👀
> Removes templates deprecated by campaign webSignup

- config/lib/helpers/contentfulEntry.js
- lib/helpers/contentfulEntry.js
- lib/helpers/defaultTopicTrigger.js
- lib/middleware/topics/single/topic-get.js
- test/lib/lib-helpers/contentfulEntry.test.js
- test/lib/lib-helpers/defaultTopicTrigger.test.js
- test/lib/middleware/topics/single/topic-get.test.js
- test/utils/factories/contentful/autoReplyTransition.js
- test/utils/factories/contentful/defaultTopicTrigger.js
Adds support to save `autoReplyTransition`, `photoPostTransition`, and `textPostTransition` entries in for the `response` reference field on a `defaultTopicTrigger` entry, allowing for keyword-specific start messaging. 
We'll manually create a new transition entry foreach  published `defaultTopicTrigger` entry that has a topic (e.g.`autoReply`, `photoPostConfig`, `textPostConfig`) saved to its `response` reference field, updating with the newly created corresponding new transition 
Also removes fetching default topic triggers for a topic in a `GET /topics/:id` request for simplicity sake. Similar to #1090 -- we can delegate finding `defaultTopicTriggers` via their transitions to Gambit Admin, as it's only for internal use.
I was testing on a draft trigger, `puppetsloth`, which is what …
> Keyword transitions

- lib/helpers/campaign.js
- test/stubs/phoenix/campaign.json
Updates the `parseStatus` campaign helper per breaking Phoenix API changes in https://github.com/DoSomething/phoenix-next/pull/1097 introduced in September.
Verify expected behavior: 
* A closed campaign like Give A Spit has a `closed `status (e.g. GET /v1/campaigns/2178?cache=false&apiKey=totallysecret)
* An open campaign like Escape The Vape has an `active` status (e.g. GET /v1/campaigns/8190?cache=false&apiKey=totallysecret)
This bug was discovered while revitalizing the list of current campaign keywords in https://github.com/DoSomething/gambit-admin/pull/80.
https://github.com/DoSomething/gambit-admin/pull/80
> Fixes campaign status per Phoenix API changes
