README.md
app/lib/sms-games/config/competitiveStoriesConfigModel.js

Minor clarifying text changes to documentation.

minor text changes to Readme and competitiveStoriesConfigModel.js

---

app/lib/ds-routing/config/startCampaignTransitionsConfigModel.js

###What does this PR do?
Fixes an incorrect and misleading comment.

comment correction

---

app/lib/reportback/test/reportback.test.js
test/ds-routing.js
test/mobilecommons.js

Fixes tests broken after #424. 
`npm test`.

add test fixes to #424

---

test/BullyText2015ABTest.js

We made some changes to our config file. This changed our test file.

fix tests for updated config

---

app/lib/bitly/bitly.js
app/lib/reportback/index.js
app/lib/reportback/test/reportback.test.js

1. Adds the bitly library to provide link shortening to the reportback flow. Now, when a user submits a reportback, the "reportback completed" message will feature a permalink to their reportback that has been shortened to 16 characters. 
2. It also refactors the `submitReportBack` function to use the Q promise library, not callbacks. 
`reportback/index.js`
`npm test`, and with the reportbacks collection on postman: 
```
{"id":"d56424ac-049d-f38d-35da-02ad8327057e","name":"SMS Report Backs - Test","timestamp":1431641139202,"requests":[{"collectionId":"d56424ac-049d-f38d-35da-02ad8327057e","id":"031d50e6-a7af-fd73-878b-857435224553","name":"4) Send why important?","description":"","url":"http://localhost:4711/reportback/test","method":"POST","headers":"","data":[{"key":"phone","value":"5555 …
```

add link shortening

---

app/config/index.js
package.json

This PR changes the hostname from Nodejitsu to Heroku. This finalizes our transition from Nodejitsu to Heroku.

change from nodejitsu host to heroku host

---

app/lib/sms-games/controllers/gameMessageHelpers.js
app/lib/sms-games/controllers/logicUserAction.js

Changes the timing of end-level messages, making sure we receive them in order.

timing fix

---

app/lib/donations/controllers/DonorsChooseDonationController.js

Change donation location from MN to St. Louis, MO. Also the cutoff date time.

change donation location from MN to St Louis, MO

---

app/lib/donations/controllers/DonorsChooseDonationController.js

Reverts DoSomething/ds-mdata-responder#501
We're turning off donations until mid-October.

Revert "change donation location from MN to St Louis, MO"

---

app/lib/donations/controllers/DonorsChooseDonationController.js

we're turning off donations until october.

merge for deploy: revert "change donation location from MN to St. Louis, MO"

---

app/lib/donations/controllers/DonorsChooseDonationController.js

Changes the donation location to Saint Louis, MO and adds a new project creation cutoff date.

change donation location to Saint Louis, MO and update API time limit

---

app/lib/donations/controllers/DonorsChooseDonationController.js

Changes donorschoose donations to be targeted nationwide. 
I've been working off my personal machine which has some configuration issues--has not yet been tested.

change donations to be nationwide [untested, do not merge]

---

app/lib/reportback/index.js

Changes reportback flow to send messages using mobilecommons.optin instead of .profile_update
There was a behavior change in the /profile_update endpoint where the specified opt-in path's message would no longer be sent. Mobile Commons may revert the change, but I'm ok with this being the long term solution too.
You'll pretty much see that everywhere `profile_update` was used, we now use the `mobilecommons.optin` call. The params for the `optin` call are different in that it expects an object with certain keys. You can find its implementation [here](https://github.com/DoSomething/ds-mdata-responder/blob/dev/mobilecommons/mobilecommons.js#L84). The end result for the user is the same, the phone number specified gets the message at the opt-in path specified.
Local testing of a dummy …

Report back messages fix

---

app/lib/puppet-sloth/index.js
app/router.js

Adds a `/puppet-sloth` route for testing & getting to know the code.

Test /puppet-sloth

---

.gitignore

Adds logs to .gitignore

---

app/lib/ds-content-api/index.js

Include reportback.source when posting to Phoenix API

---

LICENSE
package.json

Adds LICENSE

---

app/config/smsConfigsLoader.js
app/lib/ds-routing/controllers/MCRouting.js
app/lib/ds-routing/index.js
app/lib/logger/logger.js
app/lib/slothbot/index.js
mobilecommons/mobilecommons.js

Adds `verbose` and `debug` logs for [endpoints documented so far](https://github.com/DoSomething/ds-mdata-responder/wiki/api):
*  `/ds-routing/campaign-transition`
* `/ds-routing/yes-no-gateway`

LOGGING_LEVEL environment variable, adds debug logging

---

app/lib/reportback/index.js
mobilecommons/mobilecommons.js

Adds `verbose` and `debug` logging to Reportback and Mobilecommons functions, continuing logging work done in #541
Run locally in `verbose` and `debug` mode, post to your local [`reportback/:campaignName` endpoint](https://github.com/DoSomething/ds-mdata-responder/wiki/api#reportback) and inspect console logs to verify new logging.
Going through the flow by posting / debugging locally has helped uncover some gotcha's found in https://github.com/DoSomething/ds-mdata-responder/issues/506#issuecomment-236208672

Reportback logging

---

app/lib/donations/controllers/DonorsChooseDonationController.js

Useful debugging from #553 worth merging into `dev`

Adds more descriptive messages for request error vs exception

---

app/lib/ds-content-api/index.js
app/lib/reportback/index.js
server.js

Sanitize userCreate data in logs

---

app/lib/donations/controllers/DonorsChooseDonationController.js

Fixes #512 - Removes token, api password info from `logger` calls.

Donation logs cleanup

---

app/lib/donations/controllers/DonorsChooseDonationController.js

Extracts the code that inspects a `sg_users` document for the user's total of successful donations for the current Donation campaign into its own function, `getDonationCount(userDocument)`. 
Pull down and test the `/donations/donors-choose/start` endpoint locally to verify nothing's changed.
Ideally the `start` endpoint shouldn't ask the user for their information again if this is their 2nd donation (#552).  Moving the donation count check into its own function helps make the `start` function more readable, especially if we'll be adding more logic into it.
None

DonorsChooseDonationController.getDonationCount

---

app/lib/donations/controllers/DonorsChooseDonationController.js
app/lib/donations/models/donorsChooseConfigModel.js

* Adds a check for a new request `start` query string parameter. If set, start the chat by sending the relevant message (based on how much profile info we've collected for the given member)
* Adds more properties to the `donorschoose` collection to avoid hardcoding messages for invalid first name, email, and no project search results found.
* I've deployed this branch to the staging environment. Text the staging donation keyword with a reset profile to confirm that you get prompted for your zipcode, instead of getting a message back about an invalid zip.
Donation MoCo Campaign setup now requires an 2 mData's instead of 1:
1. **Donation bot: start** (posts to `/donations/donors-choose?start=true`, ignoring whatever the member has texted in and starting the conversation with relevant ask or …

Adds Donation chatbot start parameter

---

app/lib/donations/controllers/DonorsChooseDonationController.js

Fixes bug introduced in https://github.com/DoSomething/gambit/pull/584/commits/0215e241ea339e089ff7eaf149abead3a4c71a27, error is thrown when member already has an email and is repeat donating.
Go through staging flow multiple times, this branch has been deployed to staging.

Fixes TypeError in DonorsChoose chatbot if email is already set

---

app/lib/donations/controllers/DonorsChooseDonationController.js
app/lib/ds-routing/index.js
app/router.js

* Removes routes for SMS Games #525 and Tips #542 
* Adds `get`
#576 , #338

Routing updates

---

server.js

Changes server to listen on process.env.PORT

---

app/lib/ds-routing/controllers/MCRouting.js
app/lib/smsHelpers.js

Refactors logic in `smsHelpers.isYesResponse` to support values like "Of course" and "Sure"
Upon deploying to staging, text into staging Reportback Moco Campaign to verify #513 is closed
Fixes #513

Adds more options for isYesResponse

---

api/controllers/DonorsChooseBotController.js
lib/donorschoose.js

Extracts DonorsChoose API networking helpers into `lib/donorschoose`
Test that DonorsChoose bot is functional.
#599

Adds Donorschoose helper class

---

api/controllers/CampaignBotController.js

Adds support for scenario where a User already has a document created in our `users` operations collection and wants to signup for a given Campaign. 
After completing a round of testing #611, edit your user's Mongo document and remove its `campaigns` object property completely. POST again to the `v1/chatbot?bot_type=campaign&campaign=2070` to confirm a new Signup document is created and stored to your User's `campaigns` property. 
#611

Adds Signup check for existing Users

---

api/controllers/CampaignBotController.js
api/models/campaign/ReportbackSubmission.js
lib/helpers.js

* Ask user for Reportback Submission's Caption after asking for Quantity
* Asks for Why Participated only upon first Reportback (refs #614)
Manually remove your user's `campaigns` property from DB. Start up CampaignBot and verify changes.
#614

Adds and collects ReportbackSubmission.caption

---

api/controllers/CampaignBotController.js
api/router.js

* Asks for photo if our draft Reportback Submission's `image_url` property doesn't exist, sets it if we've recevied an image.
Reportback via Campaignbot and confirm `image_url` is recorded in the `reportback_submissions` document created.
Passing around our Express `req` and `res` objects per suggested answer in SO thread [about scoping data in Express](http://stackoverflow.com/a/20710437/1470725).
#606

Collects ReportbackSubmission image_url

---

api/controllers/CampaignBotController.js
api/router.js

Looks like a lot of changes, but just refactors `CampaignBotController` to use `class` instead of `prototype`. 
* Refactors `chatbot(req, res)` as `constructor(req, res)`
* Defines non-constructor functions in alphabetical order to make things easier to find
Verify CampaignBot still works.
Looking to make similar changes to the `DonorsChooseController`, and eventually add our DS [ESLint config](https://github.com/DoSomething/eslint-config).
https://github.com/DoSomething/gambit/pull/628#pullrequestreview-1381427

CampaignBotController Class

---

.gitignore
config/locals.js
wercker.yml

* Fixes `wercker.yml` to get `npm install` and `npm test` passing in Wercker to a new Gambit application.
* Fixes style errors missed in #644
* Should only be merge-able if Wercker build pipeline succeeds
👀 
Fixes #645

Wercker resurrection

---

api/controllers/CampaignBotController.js
config/router-chatbot.js

Fixes last `then`  to return our Signup model, adds debugging.
Signup for a Campaign and report back.
Introduced in #641

Fixes bug in CampaignBotController.getCurrentSignup

---

config/locals.js

https://dosomething.slack.com/archives/team-odoyle/p1477498614000186
Are groups created?
see slack msg

Comments out group creation code

---

app/models/Campaign.js
app/routes/campaigns.js

Formats Campaign model response to something a little more API
Upon stage deploy, verify http://ds-mdata-responder-staging.herokuapp.com/v1/campaigns looks 👌 
Fixes #681

Adds Campaign.formatApiResponse

---

lib/groups.js

Renaming vars based on new naming scheme, already updated the wiki & messaging groups API

Renaming config vars & header

---

lib/groups.js

tell us, what have you changed?
tell us, how can we review, to test that this works
what else?
Fixes #

Fixing typo in env

---

lib/groups.js
lib/mobilecommons.js
package.json

- Adds groups.js to lint
- Logs error if missing API key or URI
- Simplifies some error handling code
- Does the groups API still return a response?
- nope
Fixes #708

Some small cleanup work around groups

---

app/models/Signup.js
app/routes/chatbot.js

Adds broadcast ID to signup object.
This will let us query for total broadcast signups & reportbacks really easily.
Signup for a campaign via broadcast
Fixes #N/A

Adds broadcast ID to signup object

---

app/routes/campaigns.js

Just because it's not only about reminders anymore.

Minor phrasing fix.

---

app/routes/index.js

adds a status endpoint for tests to check against 
Hit the /v1/status endpoint, check you get a response
We're going to use this for automated status / ping check to test for uptime.
Fixes #

Adds status check

---

app/routes/campaigns.js

Gets filtered catch working via new Bluebird Promise to throw 422 errors when the Campaign is closed or doesn't have the relevant `messages` property set.
Verify **POST** `/v1/campaigns/:id/message` returns a 422 when expected ☝️ 
https://github.com/DoSomething/gambit/pull/789#pullrequestreview-22599167

Restores throwing 422 errors in campaign/:id/message response

---

package.json

Update New Relic to 1.37.1 which might help #811

Automatically update New Relic

---

package.json

Upgrade Node to 6.10.x

---

wercker.yml

Update Wercker to Node 6.10

---

app.json

It adds the `app.json` file required by Heroku Review Apps to work properly.
It's an Heroku generated file. It doesn't have side effects on the app. Just needs a thumbs up :)
We want to be able to test branches on Heroku without disrupting the staging app as it will be used by more teams in the near future. Using Review Apps is the best way to do that.
https://github.com/DoSomething/gambit/issues/837

Added App.json to enable Review Apps on Heroku

---

app/models/DonorsChooseBot.js
app/models/Signup.js
app/models/User.js
app/routes/campaigns.js
app/routes/chatbot.js
app/routes/donorschoosebot.js
app/routes/index.js
app/routes/signups.js
lib/mobilecommons.js
lib/phoenix.js
lib/stathat.js
server.js

Deprecates the `app.locals.stathat` in favor of a cleaner `lib/stathat` to include. 
Full test of endpoints 😬 
#848

Adds lib/stathat to deprecate app.locals.stathat

---

.eslintrc
README.md
app/models/DonorsChooseBot.js
app/models/Signup.js
app/routes/campaigns.js
app/routes/chatbot.js
app/routes/donorschoosebot.js
app/routes/index.js
app/routes/signups.js
lib/helpers.js
lib/tools/profiler.js
package.json
server.js
test/.eslintrc
test/lib/helpers.test.js
wercker.yml

Uses ava to implement the first tests in Gambit.
- Run `npm run test`. Tests should pass.
Gambit is getting tested, so should you.
https://www.pivotaltracker.com/story/show/142542259

Installed Ava and implemented first tests

---

.gitignore
package.json
wercker.yml

Adds code coverage reports to Gambit.
- Run `npm run test`
https://www.pivotaltracker.com/story/show/142542259

Adds code coverage

---

README.md
lib/helpers.js
test/lib/helpers.test.js
test/utils/stubs.js

Added more tests for the `lib/helpers` module.
- clone Gambit
- Run:

Testing continued

---

config/contentful.js
lib/contentful.js
package.json
test/.eslintrc
test/lib/contentful.test.js
test/lib/helpers.test.js
test/utils/stubs.js

Start implementing tests for the `lib/contentful` module.
- clone Gambit
- Run:

Contentful tests

---

lib/contentful.js
lib/contentfulQueryBuilder.js
package.json
test/lib/contentful.test.js
test/lib/helpers.test.js
test/stubs/contentful/get-entries-broadcast.json
test/stubs/contentful/get-entries-campaign.json
test/stubs/contentful/get-entries-keyword-for-campaign.json
test/stubs/contentful/get-entries-keyword.json
test/stubs/contentful/get-entries-keywords.json
test/utils/stubs.js

Continued implementing tests for the `lib/contentful` module.
Some moderate refactoring involved.
- clone Gambit
- Run:

Contentful tests 2

---

config/contentful.js
lib/contentful.js
lib/contentfulQueryBuilder.js
test/lib/contentful.test.js
test/stubs/contentful/get-entries-empty.json
test/utils/stubs.js

There is a good deal of refactoring of the lib/contentful tests. There are many asynchronous calls in this module which need to be atomically stubbed and managed at the test level and NOT at the beforeEach of afterEach hooks.
Also added more tests.
- clone Gambit
- Run:

Contentful tests 3

---

lib/contentful.js
test/lib/contentful.test.js
test/stubs/contentful/all-campaign-fields.json
test/stubs/contentful/get-entries-campaign-with-overrides.json
test/stubs/contentful/get-entries-default-campaign.json
test/utils/stubs.js

More refactoring of `lib/contentful`. Added more tests weeeee!.
- clone Gambit
- Run:

Contestful tests 4

---

lib/contentful.js
test/lib/contentful.test.js

Adds a test for the `mapCampaignIds` method.
- clone Gambit
- Run:
- 👀 
- [ x] Documentation added for new features/changed endpoints.
- [ x] Tested on localhost.

last method to test in the lib/contentful.js module

---

Procfile

https://devcenter.heroku.com/articles/node-memory-use#tuning-the-garbage-collector
https://devcenter.heroku.com/articles/node-best-practices#avoid-garbage
- 👀

Added another recommended flag to the Procfile web process

---

.eslintrc
app.js
app/models/User.js
app/routes/campaigns.js
app/routes/chatbot.js
app/routes/home.js
app/routes/index.js
app/routes/status.js
config/index.js
config/lib/dashbot.js
config/middleware/authenticate.js
config/required-vars.js
lib/dashbot.js
lib/helpers.js
lib/middleware/authenticate.js
lib/middleware/map-request-params.js
lib/middleware/user-create.js
lib/middleware/user-get.js
lib/middleware/user-incoming-message.js
package.json
server.js
test/lib/middleware/authenticate.test.js
test/lib/middleware/user-create.test.js
test/lib/middleware/user-get.test.js

More tests and refactoring.
- 👀 
- Run `npm run all-tests`
- Signup and Reportback with Postman

Chatbot testing

---

app/routes/chatbot.js
lib/helpers.js
lib/middleware/campaign-get.js
lib/middleware/map-request-params.js

More code moved out of the chatbot route
- 👀 
- Run `npm run all-tests`

More middleware refactoring

---

app/routes/chatbot.js
app/routes/home.js
config/env/test.js
config/index.js
lib/conversation/actions.js
lib/conversation/command.js
lib/conversation/replies.js
lib/conversation/reply-dispatcher.js
lib/helpers.js
lib/middleware/broadcast.js
lib/middleware/map-request-params.js
lib/middleware/phoenix-campaign-get.js
lib/middleware/user-get.js
lib/middleware/user-support-conversation.js
package.json
test/app/routes/chatbot.test.js
test/integration/routes/home.test.js
test/integration/routes/status.test.js
test/lib/helpers.test.js
wercker.yml

This is a biggie.
This PR introduces our first integration tests as a test drive for the more important/complex tests.
Also, it refactors the way Gambit replies back to the use. It uses a different pattern.
- 👀 
- Test all actions for which the user would get back a response: signup, signup for closed campaign, reportback flow, wrong inputs for qty, and why, no photo, broadcast y/n, etc.
- Fixes #927

Integration testing

---

lib/conversation/replies.js

Fixes stathat logging when sending replies to users.
- 👀

fix to get menu_completed showing up in stathat again

---

app/models/User.js
lib/conversation/replies.js

Adds a `last_outbound_template` property to our User model, and updates it when sending a reply back.
Post to chatbot and verify your User's `last_outbound_template` is updating accordingly.
This is in prep for adding Rivescript support into Gambit, when we'll want to reply differently based on whether the last message a User received was from Rivescript vs a Gambit message template.

User.last_outbound_template

---

package.json

Updates NewRelic to module version 2.0.0
- 👀 
- NewRelic's dashboard has been reminding us to update for a few days now

updated newrelic module to 2.0.0

---

config/lib/contentful.js

I've defined each property in #946 as a field on our Contentful Campaign content type, and set the copy in the default Campaign entry. 
This branch defines each field as a new property to our Contentful config `campaignFields` object to close #946.
Sample response:
```
data: {
messages: {
"askSignupMessage": {
"override": false,
"raw": "{{tagline}} \n\nWant to signup for {{title}}?\n\nYes or No",
"rendered": "Boost a stranger's self-esteem with just a sticky note! \n\nWant to signup for Mirror Messages?\n\nYes or No"
},
"declinedSignupMessage": {
"override": false,
"raw": "Okay, then. Text MENU if you'd like to find a different Campaign to join.",
"rendered": "Okay, then. Text MENU if you'd like to find a different Campaign to join."
},
"invalidSignupResponseMessage": {
"override": false, …
```

Campaign Menu properties

---

package.json

updated node to latest LTS 6.11.3

---

lib/conversation/replies.js
lib/helpers.js

Responds with an error and Blink suppress headers to Conversations when a legacy error occurs. 
- 👀 
Fixes #972

Troubleshooting hangups

---

package.json

Updates node version

---

documentation/README.md
documentation/endpoints/campaigns.md
test/lib/middleware/campaigns-single/render-templates.test.js
test/stubs/contentful/get-entries-campaign.json

* Restores some coverage removed in #992 
* Updates docs to remove mention of a "Gambit Campaign", just "Campaign"
👀

Render Templates test

---

README.md
package.json

* v5!
* PR/Issue 1000!
* TGM!
* 💯

v5 release

---

package.json

Troubleshooting unhappy staging build

---

package-lock.json
package.json

Troubleshooting broken building

Sets npm in package.json

---

documentation/README.md
documentation/endpoints/campaigns.md
documentation/endpoints/defaultTopicTriggers.md
documentation/endpoints/topics.md

Adds descriptions as well as example requests, responses for:
* `GET /topics`
* `GET /topics/:id`
* `GET /defaultTopicTriggers`
👀 
* #1046 
* https://github.com/DoSomething/gambit-conversations/pull/339

Documentation for topics and defaultTopicTriggers endpoints [pr]
